# Generated by Django 4.2.30 on 2026-07-19 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shared.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerBankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_account_number",
                    shared.fields.EncryptedCharField(max_length=30),
                ),
                ("ifsc_code", shared.fields.EncryptedCharField(max_length=20)),
                (
                    "account_holder_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "beneficiary_id",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("bank_account_verified", models.BooleanField(default=False)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_bank_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Owner Bank Details",
                "verbose_name_plural": "Owner Bank Details",
                "db_table": "payment_ownerbankdetails",
            },
        ),
    ]
