# Generated by Django 6.0.7 on 2026-07-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_migrate_ownerbankdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerbankdetails",
            name="created_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="ownerbankdetails",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
