sonar.organization=sbairagi
sonar.projectKey=sbairagi_RentSecureBE
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/.venv/**,**/venv/**,**/*.pyc,**/db.sqlite3,**/.github/**,**/htmlcov/**,**/coverage.xml
sonar.tests=.
sonar.test.inclusions=**/test_*.py,**/tests.py,**/*_tests.py,**/tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverageReportPaths=coverage.xml
sonar.verbose=true
sonar.pullrequest.github.repository=sbairagi/RentSecureBE
