from typing import Any, Protocol


class PaymentGateway(Protocol):
    def create_payment_link(self, rent_record: Any) -> str: ...

    def process_payout(self, rent: Any) -> dict[str, Any]: ...

    def register_beneficiary(self, bank_details: Any) -> dict[str, Any]: ...

    def delete_beneficiary(self, beneficiary_id: str) -> dict[str, Any]: ...
