# Generated by Django 4.2.30 on 2026-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_ownerbankdetails_beneficiary_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="alert_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="weekly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receive_flagged_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receive_rent_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receive_tax_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receive_vacancy_alerts",
            field=models.BooleanField(default=True),
        ),
    ]
