# Generated by Django 5.2.1 on 2025-05-24 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalailog_historicalapp_historicaluserapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_app', to=settings.AUTH_USER_MODEL),
        ),
    ]
