# Generated by Django 4.2.30 on 2026-07-19 18:43

from django.db import migrations
import shared.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_ownerbankdetails_beneficiary_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerbankdetails",
            name="bank_account_number",
            field=shared.fields.EncryptedCharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="ownerbankdetails",
            name="ifsc_code",
            field=shared.fields.EncryptedCharField(max_length=20),
        ),
    ]
