# Generated by Django 4.2.30 on 2026-05-28 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerbankdetails',
            name='account_holder_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ownerbankdetails',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
