# Generated by Django 4.2.30 on 2026-08-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_alert_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receive_voice_alerts",
            field=models.BooleanField(default=True),
        ),
    ]
