# Generated by Django 5.2 on 2026-07-22
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_ownerbankdetails_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aggregate_id", models.UUIDField(db_index=True)),
                ("aggregate_type", models.CharField(db_index=True, max_length=100)),
                ("event_type", models.CharField(db_index=True, max_length=255)),
                ("event_version", models.CharField(default="1.0", max_length=20)),
                ("payload", models.JSONField()),
                ("headers", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROCESSING", "PROCESSING"),
                            ("PUBLISHED", "PUBLISHED"),
                            ("FAILED", "FAILED"),
                            ("DEAD_LETTER", "DEAD_LETTER"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retry", models.PositiveIntegerField(default=6)),
                (
                    "next_retry_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "outbox_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["status", "next_retry_at"],
                name="outbox_event_status_next_retry_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["aggregate_id", "event_type"],
                name="outbox_event_aggregate_eventtype_idx",
            ),
        ),
    ]
