# Generated by Django 4.2.30 on 2026-08-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_voice_alert_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="greeting_prefix",
            field=models.CharField(
                blank=True,
                help_text="Custom greeting for WhatsApp messages, e.g., 'from Gokul PG'",
                max_length=100,
            ),
        ),
    ]
