# Generated by Django 4.2.30 on 2026-08-02 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_greeting_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reminder_time",
            field=models.TimeField(
                default=datetime.time(9, 0),
                help_text="Preferred time to send WhatsApp rent and tax reminders",
            ),
        ),
    ]
