# Generated by Django 4.2.30 on 2026-08-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_reminder_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rent_reminders_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable or disable WhatsApp rent reminders for this owner's renters",
            ),
        ),
    ]
