# Generated by Django 4.2.30 on 2026-08-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_rent_reminders_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="other_income",
            field=models.PositiveIntegerField(
                default=0, help_text="Other annual income for ITR calculations"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="salary",
            field=models.PositiveIntegerField(
                default=0, help_text="Annual salary income for ITR calculations"
            ),
        ),
    ]
