# Generated by Django 4.2.30 on 2026-08-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_add_analytics_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caconnectionrequest",
            options={"ordering": ["-requested_at"]},
        ),
        migrations.AlterField(
            model_name="caconnectionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONTACTED", "Contacted"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
