# Generated by Django 6.0.7 on 2026-07-19 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rent_alerts_whatsapp", models.BooleanField(default=True)),
                ("rent_alerts_email", models.BooleanField(default=True)),
                ("monthly_summary_email", models.BooleanField(default=True)),
                ("monthly_summary_whatsapp", models.BooleanField(default=False)),
                ("payout_alerts_whatsapp", models.BooleanField(default=True)),
                ("payout_alerts_email", models.BooleanField(default=False)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
