# Generated by Django 4.2.30 on 2026-08-02 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_add_renter_rating_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "Text"), ("audio", "Audio")], max_length=10
                    ),
                ),
                ("message_content", models.TextField()),
                ("media_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SENT", "Sent"), ("FAILED", "Failed")],
                        default="SENT",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "rent_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_logs",
                        to="properties.rentrecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
