# Generated by Django 4.2.30 on 2026-08-02 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notification", "0002_add_whatsapp_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsapplog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatsapp_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
