# Generated by Django 4.2.30 on 2026-08-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_whatsapp_log_user_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapplog",
            name="last_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="whatsapplog",
            name="status",
            field=models.CharField(
                choices=[
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("RETRYING", "Retrying"),
                    ("PERMANENT_FAILED", "Permanent Failed"),
                ],
                default="SENT",
                max_length=20,
            ),
        ),
    ]
