# Generated by Django 4.2.30 on 2026-07-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_migrate_notificationpreference"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationpreference",
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
    ]
