# Generated by Django 4.2.30 on 2026-08-27 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notification", "0005_enhance_notification_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_31cda9_idx",
            old_name="notification_user_read_created_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_419f0d_idx",
            old_name="notification_user_type_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_6992c3_idx",
            old_name="notification_user_resource_idx",
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="device_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="devicetoken",
            unique_together={("user", "token")},
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["user", "active"], name="notificatio_user_id_64a0ef_idx"
            ),
        ),
    ]
