from __future__ import annotations

DEFAULT_BATCH_SIZE = 100
DEFAULT_MAX_RETRY = 6
DEFAULT_RETENTION_DAYS = 30
DEFAULT_DISPATCH_INTERVAL = 60

BACKOFF_BASE_SECONDS = 60
BACKOFF_MULTIPLIER = 2
BACKOFF_MAX_SECONDS = 32 * 60

__all__ = [
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_MAX_RETRY",
    "DEFAULT_RETENTION_DAYS",
    "DEFAULT_DISPATCH_INTERVAL",
    "BACKOFF_BASE_SECONDS",
    "BACKOFF_MULTIPLIER",
    "BACKOFF_MAX_SECONDS",
]
