#!/usr/bin/env python3
"""UML Guardian - detects UML drift and missing diagrams."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


class UMLGuardian:
    """Detects UML drift and missing diagrams."""

    def __init__(self, root: Path):
        self.root = root
        self.violations: list[str] = []

    def check_required_diagrams_exist(self) -> bool:
        """Check that required diagrams exist."""
        required_diagrams = [
            "docs/uml/generated/plantuml/class-diagram.puml",
            "docs/uml/generated/plantuml/component-diagram.puml",
            "docs/uml/generated/mermaid/class-diagram.mmd",
            "docs/uml/generated/mermaid/ci-flow.mmd",
            "docs/diagrams/generated/c4/c4-context.puml",
            "docs/diagrams/generated/c4/c4-container.puml",
            "docs/uml/generated/domain/er-diagram.puml",
            "docs/diagrams/generated/flows/authentication-flow.puml",
            "docs/diagrams/generated/flows/payment-flow.puml",
            "docs/diagrams/generated/flows/notification-flow.puml",
            "docs/diagrams/generated/infrastructure/aws-deployment.puml",
            "docs/diagrams/generated/infrastructure/cicd-pipeline.puml",
            "docs/uml/generated/ddd/ddd-bounded-contexts.puml",
        ]

        missing = [d for d in required_diagrams if not (self.root / d).exists()]
        if missing:
            for diagram in missing:
                print(f"[WARN] Missing diagram (generated by CI): {diagram}")
            return True

        return True

    def check_uml_syntax(self) -> bool:
        """Check PlantUML syntax."""
        plantuml_dir = self.root / "docs/uml/generated/plantuml"
        if not plantuml_dir.exists():
            return True

        for puml_file in plantuml_dir.glob("*.puml"):
            content = puml_file.read_text()
            if "@startuml" not in content:
                self.violations.append(f"Missing @startuml in {puml_file.name}")
            if "@enduml" not in content:
                self.violations.append(f"Missing @enduml in {puml_file.name}")

        return len(self.violations) == 0

    def check_mermaid_syntax(self) -> bool:
        """Check Mermaid syntax."""
        mermaid_dir = self.root / "docs/uml/generated/mermaid"
        if not mermaid_dir.exists():
            return True

        valid_types = [
            "graph",
            "flowchart",
            "sequenceDiagram",
            "classDiagram",
            "stateDiagram",
        ]
        for mmd_file in mermaid_dir.glob("*.mmd"):
            content = mmd_file.read_text()
            if not any(content.startswith(t) for t in valid_types):
                self.violations.append(
                    f"Invalid Mermaid diagram type in {mmd_file.name}"
                )

        return len(self.violations) == 0

    def check_diagram_drift(self) -> bool:
        """Check if diagrams are outdated compared to source."""
        diagram_dir = self.root / "docs/uml"
        if not diagram_dir.exists():
            return True

        # Simple check: if diagrams exist, they're considered valid
        # In a real implementation, this would compare hashes
        return True

    def run_all_checks(self) -> int:
        """Run all UML guardian checks."""
        checks = [
            ("Required Diagrams", self.check_required_diagrams_exist),
            ("PlantUML Syntax", self.check_uml_syntax),
            ("Mermaid Syntax", self.check_mermaid_syntax),
            ("Diagram Drift", self.check_diagram_drift),
        ]

        all_passed = True
        for name, check in checks:
            try:
                passed = check()
                status = "PASS" if passed else "FAIL"
                print(f"[{status}] {name}")
                if not passed:
                    all_passed = False
            except Exception as e:
                print(f"[ERROR] {name}: {e}")
                all_passed = False

        if self.violations:
            print("\nViolations:")
            for violation in self.violations:
                print(f"  - {violation}")

        return 0 if all_passed else 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Run UML guardian checks")
    parser.add_argument("--root", type=str, default=".", help="Repository root")
    args = parser.parse_args()

    guardian = UMLGuardian(Path(args.root))
    return guardian.run_all_checks()


if __name__ == "__main__":
    sys.exit(main())
