# Generated by Django 4.2.30 on 2026-06-22 16:43

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Building name or identifier (e.g., 'Sunshine Complex', 'Tower A')",
                        max_length=255,
                    ),
                ),
                (
                    "address_line",
                    models.CharField(
                        help_text="Street address of the building", max_length=255
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True,
                        help_text="City where building is located",
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(help_text="State or province", max_length=100),
                ),
                ("country", models.CharField(help_text="Country name", max_length=100)),
                (
                    "postal_code",
                    models.CharField(help_text="ZIP or postal code", max_length=10),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete: archived buildings are excluded from queries",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this building was added to the system",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Owner of this building",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CareTaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Caretaker full name", max_length=100),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone",
                    models.CharField(
                        help_text="Primary phone",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        help_text="Alternate phone",
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "joining_date",
                    models.DateField(db_index=True, help_text="Date of joining"),
                ),
                ("leaving_date", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Currently active?"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Caretaker",
                "verbose_name_plural": "Caretakers",
                "ordering": ["-joining_date"],
            },
        ),
        migrations.CreateModel(
            name="Renter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(help_text="Renter's full name", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Renter's email for receipts and notifications",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Primary phone number",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        help_text="Alternate phone number",
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact number",
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "renter_image",
                    models.ImageField(
                        blank=True,
                        help_text="Photo of renter",
                        null=True,
                        upload_to="renter_image/",
                    ),
                ),
                (
                    "id_proof",
                    models.FileField(
                        help_text="Renter's ID proof document",
                        upload_to="id_proofs/renter/",
                    ),
                ),
                (
                    "rent_agreement",
                    models.FileField(
                        help_text="Rent agreement document", upload_to="agreements/"
                    ),
                ),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Rent amount", max_digits=10
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, help_text="Rental start date"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Rental end date", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is renter currently active?"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="For WhatsApp messages",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "rent_due_date",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        help_text="Required for rent reminder",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Move in Date"),
                ),
                ("late_payment_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("missed_rents", models.PositiveIntegerField(default=0)),
                ("is_flagged", models.BooleanField(default=False)),
                ("flagged_reason", models.TextField(blank=True, null=True)),
                ("is_agreement_revoked", models.BooleanField(default=False)),
                ("revocation_reason", models.TextField(blank=True, null=True)),
                ("revoked_by_owner", models.BooleanField(default=False)),
                ("revoked_on", models.DateTimeField(blank=True, null=True)),
                ("vacated_on", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("notice_period", "Notice Period"),
                            ("revoked", "Revoked"),
                            ("deactivated", "Deactivated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notice_start_date", models.DateField(blank=True, null=True)),
                (
                    "final_invoice_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "onboarding_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Invite"),
                            ("link_sent", "Link Sent"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        help_text="Renter self-onboarding progress",
                        max_length=20,
                    ),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="not_started",
                        help_text="KYC verification status",
                        max_length=20,
                    ),
                ),
                (
                    "onboarding_token",
                    models.CharField(
                        blank=True,
                        help_text="Secure token for onboarding link",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "onboarding_link_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the onboarding link was sent to renter",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit identifier (e.g., '101', 'Flat A', 'Shop 5')",
                        max_length=100,
                    ),
                ),
                (
                    "building_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name of building (cached for performance)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("land", "Land"),
                            ("flat", "Flat/Apartment"),
                            ("commercial_shop", "Commercial Shop"),
                            ("house", "House"),
                            ("villa", "Villa"),
                            ("office", "Office"),
                            ("paying_guest", "Paying Guest / PG"),
                        ],
                        help_text="Type of property",
                        max_length=50,
                    ),
                ),
                (
                    "address_line",
                    models.CharField(help_text="Street address", max_length=255),
                ),
                (
                    "landmark",
                    models.CharField(
                        blank=True,
                        help_text="Nearby landmark for easy identification",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(db_index=True, help_text="City", max_length=100),
                ),
                ("state", models.CharField(help_text="State/Province", max_length=100)),
                ("country", models.CharField(help_text="Country", max_length=100)),
                (
                    "postal_code",
                    models.CharField(help_text="ZIP or postal code", max_length=20),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude coordinate (-90 to 90)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude coordinate (-180 to 180)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("vacant", "Vacant"), ("occupied", "Occupied")],
                        default="vacant",
                        help_text="Current occupancy status",
                        max_length=20,
                    ),
                ),
                (
                    "is_vacant",
                    models.BooleanField(
                        default=True, help_text="Denormalized: True if status=='vacant'"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether property details have been verified",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete: archived units are hidden from listings",
                    ),
                ),
                (
                    "last_vacated_at",
                    models.DateField(
                        blank=True,
                        help_text="Date when the unit became vacant because no active renter remained",
                        null=True,
                    ),
                ),
                (
                    "rent_due_reminder",
                    models.BooleanField(
                        default=True, help_text="Enable automated rent due reminders"
                    ),
                ),
                (
                    "agreement_expiry_reminder",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automated agreement expiry reminders",
                    ),
                ),
                (
                    "maintenance_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about maintenance or issues",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the unit",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent building (optional for standalone units)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="units",
                        to="properties.building",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Property owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnitVacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("renovation", "Under Renovation"),
                            ("cleaning", "Cleaning/Maintenance"),
                            ("between_renters", "Between Renters"),
                            ("long_term_vacancy", "Long-Term Vacancy"),
                            ("other", "Other Reason"),
                        ],
                        help_text="Reason for vacancy",
                        max_length=100,
                    ),
                ),
                (
                    "noted_on",
                    models.DateField(
                        auto_now_add=True, help_text="Date vacancy was recorded"
                    ),
                ),
                (
                    "unit",
                    models.OneToOneField(
                        help_text="Unit that became vacant",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit Vacancy",
                "verbose_name_plural": "Unit Vacancies",
                "ordering": ["-noted_on"],
            },
        ),
        migrations.CreateModel(
            name="RentReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        help_text="EXAMPLE: PRE, DUE, LATE", max_length=20
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.renter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Rent amount paid", max_digits=10
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("upi", "UPI"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("online", "Online Payment"),
                            ("other", "Other"),
                        ],
                        help_text="Mode of payment used",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                (
                    "paid_on",
                    models.DateField(
                        blank=True, help_text="Date when payment was made", null=True
                    ),
                ),
                (
                    "due_date",
                    models.DateField(db_index=True, help_text="Rent due date"),
                ),
                (
                    "late_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Late fee applied",
                        max_digits=10,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Any discount given",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment gateway / bank ref",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payout_status",
                    models.CharField(
                        default="PENDING",
                        help_text="Payout transfer status",
                        max_length=20,
                    ),
                ),
                (
                    "payout_reference",
                    models.CharField(
                        blank=True,
                        help_text="Payout gateway reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payment_link",
                    models.CharField(
                        blank=True,
                        help_text="Payment gateway link",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "invoice_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Generated rent receipt PDF",
                        null=True,
                        upload_to="invoices/",
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay order reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payout_retries",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of payout retry attempts"
                    ),
                ),
                (
                    "last_payout_retry",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last payout retry",
                        null=True,
                    ),
                ),
                (
                    "payout_retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Cumulative payout retry count"
                    ),
                ),
                (
                    "adjustment_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for late fee or adjustment",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "renter",
                    models.ForeignKey(
                        help_text="Renter who made the payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rent_records",
                        to="properties.renter",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit this rent record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rent_records",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rent Record",
                "verbose_name_plural": "Rent Records",
                "ordering": ["-due_date"],
            },
        ),
        migrations.AddField(
            model_name="renter",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="renters",
                to="properties.unit",
            ),
        ),
        migrations.AddField(
            model_name="renter",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renter_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RentAgreementDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="auto_agreements/")),
                (
                    "leegality_document_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("owner_signed", models.BooleanField(default=False)),
                ("renter_signed", models.BooleanField(default=False)),
                (
                    "renter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.renter",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rent_agreement_draft",
                        to="properties.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyTaxRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("paid", models.BooleanField(default=False)),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_records",
                        to="properties.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoliceVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="rent_agreements/")),
                (
                    "renter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.renter",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="police_verification",
                        to="properties.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalUnit",
            fields=[
                ("id", models.IntegerField(blank=True, db_index=True)),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit identifier (e.g., '101', 'Flat A', 'Shop 5')",
                        max_length=100,
                    ),
                ),
                (
                    "building_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name of building (cached for performance)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("land", "Land"),
                            ("flat", "Flat/Apartment"),
                            ("commercial_shop", "Commercial Shop"),
                            ("house", "House"),
                            ("villa", "Villa"),
                            ("office", "Office"),
                            ("paying_guest", "Paying Guest / PG"),
                        ],
                        help_text="Type of property",
                        max_length=50,
                    ),
                ),
                (
                    "address_line",
                    models.CharField(help_text="Street address", max_length=255),
                ),
                (
                    "landmark",
                    models.CharField(
                        blank=True,
                        help_text="Nearby landmark for easy identification",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(db_index=True, help_text="City", max_length=100),
                ),
                ("state", models.CharField(help_text="State/Province", max_length=100)),
                ("country", models.CharField(help_text="Country", max_length=100)),
                (
                    "postal_code",
                    models.CharField(help_text="ZIP or postal code", max_length=20),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude coordinate (-90 to 90)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude coordinate (-180 to 180)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("vacant", "Vacant"), ("occupied", "Occupied")],
                        default="vacant",
                        help_text="Current occupancy status",
                        max_length=20,
                    ),
                ),
                (
                    "is_vacant",
                    models.BooleanField(
                        default=True, help_text="Denormalized: True if status=='vacant'"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether property details have been verified",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete: archived units are hidden from listings",
                    ),
                ),
                (
                    "last_vacated_at",
                    models.DateField(
                        blank=True,
                        help_text="Date when the unit became vacant because no active renter remained",
                        null=True,
                    ),
                ),
                (
                    "rent_due_reminder",
                    models.BooleanField(
                        default=True, help_text="Enable automated rent due reminders"
                    ),
                ),
                (
                    "agreement_expiry_reminder",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automated agreement expiry reminders",
                    ),
                ),
                (
                    "maintenance_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about maintenance or issues",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the unit",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Parent building (optional for standalone units)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="properties.building",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Property owner",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Unit",
                "verbose_name_plural": "historical Units",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRenter",
            fields=[
                ("id", models.IntegerField(blank=True, db_index=True)),
                (
                    "name",
                    models.CharField(help_text="Renter's full name", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Renter's email for receipts and notifications",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Primary phone number",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        help_text="Alternate phone number",
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact number",
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "renter_image",
                    models.TextField(
                        blank=True,
                        help_text="Photo of renter",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "id_proof",
                    models.TextField(
                        help_text="Renter's ID proof document", max_length=100
                    ),
                ),
                (
                    "rent_agreement",
                    models.TextField(
                        help_text="Rent agreement document", max_length=100
                    ),
                ),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Rent amount", max_digits=10
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, help_text="Rental start date"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Rental end date", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is renter currently active?"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="For WhatsApp messages",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "rent_due_date",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        help_text="Required for rent reminder",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Move in Date"
                    ),
                ),
                ("late_payment_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("missed_rents", models.PositiveIntegerField(default=0)),
                ("is_flagged", models.BooleanField(default=False)),
                ("flagged_reason", models.TextField(blank=True, null=True)),
                ("is_agreement_revoked", models.BooleanField(default=False)),
                ("revocation_reason", models.TextField(blank=True, null=True)),
                ("revoked_by_owner", models.BooleanField(default=False)),
                ("revoked_on", models.DateTimeField(blank=True, null=True)),
                ("vacated_on", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("notice_period", "Notice Period"),
                            ("revoked", "Revoked"),
                            ("deactivated", "Deactivated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notice_start_date", models.DateField(blank=True, null=True)),
                (
                    "final_invoice_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "onboarding_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Invite"),
                            ("link_sent", "Link Sent"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        help_text="Renter self-onboarding progress",
                        max_length=20,
                    ),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="not_started",
                        help_text="KYC verification status",
                        max_length=20,
                    ),
                ),
                (
                    "onboarding_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Secure token for onboarding link",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "onboarding_link_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the onboarding link was sent to renter",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="properties.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical renter",
                "verbose_name_plural": "historical renters",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalExtraCharge",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Charge name, e.g. Electricity or Maintenance",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DUE", "Due"),
                            ("PAID", "Paid"),
                            ("MISSED", "Missed"),
                        ],
                        default="DUE",
                        help_text="Current payment status for this extra charge",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="properties.renter",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical extra charge",
                "verbose_name_plural": "historical extra charges",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCareTaker",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Caretaker full name", max_length=100),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone",
                    models.CharField(
                        help_text="Primary phone",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        help_text="Alternate phone",
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "joining_date",
                    models.DateField(db_index=True, help_text="Date of joining"),
                ),
                ("leaving_date", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Currently active?"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="properties.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Caretaker",
                "verbose_name_plural": "historical Caretakers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ExtraCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Charge name, e.g. Electricity or Maintenance",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DUE", "Due"),
                            ("PAID", "Paid"),
                            ("MISSED", "Missed"),
                        ],
                        default="DUE",
                        help_text="Current payment status for this extra charge",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_charges",
                        to="properties.renter",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_charges",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="CareTakerAssignmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(help_text="assigned / unassigned", max_length=20),
                ),
                ("action_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "caretaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.caretaker",
                    ),
                ),
            ],
            options={
                "ordering": ["-action_date"],
            },
        ),
        migrations.AddField(
            model_name="caretaker",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caretakers",
                to="properties.unit",
            ),
        ),
        migrations.AddField(
            model_name="caretaker",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="caretaker_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ArchivedRenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("agreement_pdf", models.FileField(upload_to="archived/agreements/")),
                ("police_pdf", models.FileField(upload_to="archived/police/")),
                ("property_images", models.JSONField(default=list)),
                (
                    "final_invoice",
                    models.FileField(upload_to="archived/final_invoice/"),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "renter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.renter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgreementRevocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.renter",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnitImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Unit image/photo", upload_to="unit_images/"
                    ),
                ),
                (
                    "image_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="SHA256 hash for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When image was uploaded"
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated renter (optional - for condition check-in/out photos)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="properties.renter",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit these images belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit Image",
                "verbose_name_plural": "Unit Images",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["unit", "uploaded_at"],
                        name="properties__unit_id_e0dbd7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UnitDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        help_text="Uploaded document file", upload_to="unit_documents/"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="SHA256 hash for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When document was uploaded"
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated renter (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="properties.renter",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit this document belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit Document",
                "verbose_name_plural": "Unit Documents",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["unit", "uploaded_at"],
                        name="properties__unit_id_9df03d_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["city", "owner"], name="properties__city_d4147d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["owner", "is_archived"], name="properties__owner_i_f42b55_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("owner", "unit", "building", "address_line")},
        ),
        migrations.AlterUniqueTogether(
            name="rentrecord",
            unique_together={("unit", "due_date")},
        ),
        migrations.AlterUniqueTogether(
            name="renter",
            unique_together={("unit", "phone")},
        ),
        migrations.AlterUniqueTogether(
            name="rentagreementdraft",
            unique_together={("renter", "unit")},
        ),
        migrations.AlterUniqueTogether(
            name="policeverification",
            unique_together={("renter", "unit")},
        ),
        migrations.AddIndex(
            model_name="extracharge",
            index=models.Index(fields=["status"], name="properties__status_651d5d_idx"),
        ),
        migrations.AddIndex(
            model_name="extracharge",
            index=models.Index(
                fields=["due_date"], name="properties__due_dat_b5794c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="caretaker",
            unique_together={("unit", "phone")},
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["owner", "is_archived"], name="properties__owner_i_1b102b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["city", "owner"], name="properties__city_35cafc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="building",
            unique_together={("name", "address_line", "city", "owner")},
        ),
    ]
