# Generated by Django 4.2.30 on 2026-06-23 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalRentRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Rent amount paid", max_digits=10
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("upi", "UPI"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("online", "Online Payment"),
                            ("other", "Other"),
                        ],
                        help_text="Mode of payment used",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                (
                    "paid_on",
                    models.DateField(
                        blank=True, help_text="Date when payment was made", null=True
                    ),
                ),
                (
                    "due_date",
                    models.DateField(db_index=True, help_text="Rent due date"),
                ),
                (
                    "late_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Late fee applied",
                        max_digits=10,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Any discount given",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment gateway / bank ref",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payout_status",
                    models.CharField(
                        default="PENDING",
                        help_text="Payout transfer status",
                        max_length=20,
                    ),
                ),
                (
                    "payout_reference",
                    models.CharField(
                        blank=True,
                        help_text="Payout gateway reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payment_link",
                    models.CharField(
                        blank=True,
                        help_text="Payment gateway link",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "invoice_pdf",
                    models.TextField(
                        blank=True,
                        help_text="Generated rent receipt PDF",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay order reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payout_retries",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of payout retry attempts"
                    ),
                ),
                (
                    "last_payout_retry",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last payout retry",
                        null=True,
                    ),
                ),
                (
                    "payout_retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Cumulative payout retry count"
                    ),
                ),
                (
                    "adjustment_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for late fee or adjustment",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Renter who made the payment",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="properties.renter",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Unit this rent record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Rent Record",
                "verbose_name_plural": "historical Rent Records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
