# Generated by Django 4.2.30 on 2026-05-14 19:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_historicalrenter_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['-created_at'], 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterModelOptions(
            name='caretaker',
            options={'ordering': ['-start_date'], 'verbose_name': 'Caretaker', 'verbose_name_plural': 'Caretakers'},
        ),
        migrations.AlterModelOptions(
            name='historicalcaretaker',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Caretaker', 'verbose_name_plural': 'historical Caretakers'},
        ),
        migrations.AlterModelOptions(
            name='historicalunit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Unit', 'verbose_name_plural': 'historical Units'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterModelOptions(
            name='unitdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Unit Document', 'verbose_name_plural': 'Unit Documents'},
        ),
        migrations.AlterModelOptions(
            name='unitimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Unit Image', 'verbose_name_plural': 'Unit Images'},
        ),
        migrations.AlterModelOptions(
            name='unitvacancy',
            options={'ordering': ['-noted_on'], 'verbose_name': 'Unit Vacancy', 'verbose_name_plural': 'Unit Vacancies'},
        ),
        migrations.RemoveIndex(
            model_name='unit',
            name='properties__city_dc07b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='unit',
            name='properties__owner_i_4b6a80_idx',
        ),
        migrations.AddField(
            model_name='historicalunit',
            name='last_vacated_at',
            field=models.DateField(blank=True, help_text='Date when the unit became vacant because no active renter remained', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='last_vacated_at',
            field=models.DateField(blank=True, help_text='Date when the unit became vacant because no active renter remained', null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='address_line',
            field=models.CharField(help_text='Street address of the building', max_length=255),
        ),
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.CharField(db_index=True, help_text='City where building is located', max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='country',
            field=models.CharField(help_text='Country name', max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this building was added to the system'),
        ),
        migrations.AlterField(
            model_name='building',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft-delete: archived buildings are excluded from queries'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(help_text="Building name or identifier (e.g., 'Sunshine Complex', 'Tower A')", max_length=255),
        ),
        migrations.AlterField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(help_text='Owner of this building', on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='building',
            name='postal_code',
            field=models.CharField(help_text='ZIP or postal code', max_length=10),
        ),
        migrations.AlterField(
            model_name='building',
            name='state',
            field=models.CharField(help_text='State or province', max_length=100),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='address_line',
            field=models.CharField(help_text='Residential address', max_length=255),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate phone number (optional)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='caretaker_image',
            field=models.ImageField(blank=True, help_text='Photo of caretaker for identification', null=True, upload_to='caretaker_image/'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='city',
            field=models.CharField(db_index=True, help_text='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Name of emergency contact person', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='emergency_contact_number',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='end_date',
            field=models.DateField(blank=True, help_text='When caretaker ended (null if active)', null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='id_proof',
            field=models.FileField(help_text='Government ID proof (Aadhaar, PAN, etc.)', upload_to='id_proof/caretaker/'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about caretaker', null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='phone',
            field=models.CharField(db_index=True, help_text='Primary phone number (+country_code format)', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='postal_code',
            field=models.CharField(help_text='ZIP or postal code', max_length=20),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, help_text='When caretaker started', null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='state',
            field=models.CharField(help_text='State/Province', max_length=100),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='unit',
            field=models.ForeignKey(help_text='Unit managed by this caretaker', on_delete=django.db.models.deletion.CASCADE, related_name='caretakers', to='properties.unit'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for quick communication', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='address_line',
            field=models.CharField(help_text='Residential address', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate phone number (optional)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='caretaker_image',
            field=models.TextField(blank=True, help_text='Photo of caretaker for identification', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='city',
            field=models.CharField(db_index=True, help_text='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Name of emergency contact person', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='emergency_contact_number',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='end_date',
            field=models.DateField(blank=True, help_text='When caretaker ended (null if active)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='id_proof',
            field=models.TextField(help_text='Government ID proof (Aadhaar, PAN, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about caretaker', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='phone',
            field=models.CharField(db_index=True, help_text='Primary phone number (+country_code format)', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='postal_code',
            field=models.CharField(help_text='ZIP or postal code', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, help_text='When caretaker started', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='state',
            field=models.CharField(help_text='State/Province', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Unit managed by this caretaker', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='properties.unit'),
        ),
        migrations.AlterField(
            model_name='historicalcaretaker',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for quick communication', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='agreement_expiry_reminder',
            field=models.BooleanField(default=True, help_text='Enable automated agreement expiry reminders'),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='building',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Parent building (optional for standalone units)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='properties.building'),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='building_name',
            field=models.CharField(blank=True, help_text='Display name of building (cached for performance)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='city',
            field=models.CharField(db_index=True, help_text='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft-delete: archived units are hidden from listings'),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='is_vacant',
            field=models.BooleanField(default=True, help_text="Denormalized: True if status=='vacant'"),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether property details have been verified'),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark for easy identification', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate (-90 to 90)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate (-180 to 180)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='maintenance_notes',
            field=models.TextField(blank=True, help_text='Internal notes about maintenance or issues', null=True),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the unit', null=True),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Property owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='postal_code',
            field=models.CharField(help_text='ZIP or postal code', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='rent_due_reminder',
            field=models.BooleanField(default=True, help_text='Enable automated rent due reminders'),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='state',
            field=models.CharField(help_text='State/Province', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='vacant', help_text='Current occupancy status', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='unit',
            field=models.CharField(help_text="Unit identifier (e.g., '101', 'Flat A', 'Shop 5')", max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='unit_type',
            field=models.CharField(choices=[('land', 'Land'), ('flat', 'Flat/Apartment'), ('commercial_shop', 'Commercial Shop'), ('house', 'House'), ('villa', 'Villa'), ('office', 'Office'), ('paying_guest', 'Paying Guest / PG')], help_text='Type of property', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='agreement_expiry_reminder',
            field=models.BooleanField(default=True, help_text='Enable automated agreement expiry reminders'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Parent building (optional for standalone units)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='properties.building'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='building_name',
            field=models.CharField(blank=True, help_text='Display name of building (cached for performance)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='city',
            field=models.CharField(db_index=True, help_text='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft-delete: archived units are hidden from listings'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_vacant',
            field=models.BooleanField(default=True, help_text="Denormalized: True if status=='vacant'"),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether property details have been verified'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark for easy identification', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate (-90 to 90)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate (-180 to 180)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='maintenance_notes',
            field=models.TextField(blank=True, help_text='Internal notes about maintenance or issues', null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the unit', null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(help_text='Property owner', on_delete=django.db.models.deletion.CASCADE, related_name='units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='postal_code',
            field=models.CharField(help_text='ZIP or postal code', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rent_due_reminder',
            field=models.BooleanField(default=True, help_text='Enable automated rent due reminders'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='state',
            field=models.CharField(help_text='State/Province', max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='vacant', help_text='Current occupancy status', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(help_text="Unit identifier (e.g., '101', 'Flat A', 'Shop 5')", max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('land', 'Land'), ('flat', 'Flat/Apartment'), ('commercial_shop', 'Commercial Shop'), ('house', 'House'), ('villa', 'Villa'), ('office', 'Office'), ('paying_guest', 'Paying Guest / PG')], help_text='Type of property', max_length=50),
        ),
        migrations.AlterField(
            model_name='unitdocument',
            name='document',
            field=models.FileField(help_text='Uploaded document file', upload_to='unit_documents/'),
        ),
        migrations.AlterField(
            model_name='unitdocument',
            name='file_hash',
            field=models.CharField(db_index=True, editable=False, help_text='SHA256 hash for deduplication', max_length=64),
        ),
        migrations.AlterField(
            model_name='unitdocument',
            name='renter',
            field=models.ForeignKey(blank=True, help_text='Associated renter (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='properties.renter'),
        ),
        migrations.AlterField(
            model_name='unitdocument',
            name='unit',
            field=models.ForeignKey(help_text='Unit this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.unit'),
        ),
        migrations.AlterField(
            model_name='unitdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When document was uploaded'),
        ),
        migrations.AlterField(
            model_name='unitimage',
            name='image',
            field=models.ImageField(help_text='Unit image/photo', upload_to='unit_images/'),
        ),
        migrations.AlterField(
            model_name='unitimage',
            name='image_hash',
            field=models.CharField(db_index=True, editable=False, help_text='SHA256 hash for deduplication', max_length=64),
        ),
        migrations.AlterField(
            model_name='unitimage',
            name='renter',
            field=models.ForeignKey(blank=True, help_text='Associated renter (optional - for condition check-in/out photos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='properties.renter'),
        ),
        migrations.AlterField(
            model_name='unitimage',
            name='unit',
            field=models.ForeignKey(help_text='Unit these images belong to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.unit'),
        ),
        migrations.AlterField(
            model_name='unitimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When image was uploaded'),
        ),
        migrations.AlterField(
            model_name='unitvacancy',
            name='noted_on',
            field=models.DateField(auto_now_add=True, help_text='Date vacancy was recorded'),
        ),
        migrations.AlterField(
            model_name='unitvacancy',
            name='reason',
            field=models.CharField(choices=[('renovation', 'Under Renovation'), ('cleaning', 'Cleaning/Maintenance'), ('between_renters', 'Between Renters'), ('long_term_vacancy', 'Long-Term Vacancy'), ('other', 'Other Reason')], help_text='Reason for vacancy', max_length=100),
        ),
        migrations.AlterField(
            model_name='unitvacancy',
            name='unit',
            field=models.OneToOneField(help_text='Unit that became vacant', on_delete=django.db.models.deletion.CASCADE, to='properties.unit'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['owner', 'is_archived'], name='properties__owner_i_1b102b_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['city', 'owner'], name='properties__city_35cafc_idx'),
        ),
        migrations.AddIndex(
            model_name='caretaker',
            index=models.Index(fields=['unit', 'start_date'], name='properties__unit_id_2041da_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['city', 'owner'], name='properties__city_d4147d_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['owner', 'is_archived'], name='properties__owner_i_f42b55_idx'),
        ),
        migrations.AddIndex(
            model_name='unitdocument',
            index=models.Index(fields=['unit', 'uploaded_at'], name='properties__unit_id_9df03d_idx'),
        ),
        migrations.AddIndex(
            model_name='unitimage',
            index=models.Index(fields=['unit', 'uploaded_at'], name='properties__unit_id_e0dbd7_idx'),
        ),
    ]
