# Generated by Django 4.2.30 on 2026-05-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_building_options_alter_caretaker_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrenter',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_started', help_text='KYC verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='onboarding_link_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the onboarding link was sent to renter', null=True),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='onboarding_status',
            field=models.CharField(choices=[('pending', 'Pending Invite'), ('link_sent', 'Link Sent'), ('completed', 'Completed')], default='pending', help_text='Renter self-onboarding progress', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='onboarding_token',
            field=models.CharField(blank=True, db_index=True, help_text='Secure token for onboarding link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_started', help_text='KYC verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='renter',
            name='onboarding_link_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the onboarding link was sent to renter', null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='onboarding_status',
            field=models.CharField(choices=[('pending', 'Pending Invite'), ('link_sent', 'Link Sent'), ('completed', 'Completed')], default='pending', help_text='Renter self-onboarding progress', max_length=20),
        ),
        migrations.AddField(
            model_name='renter',
            name='onboarding_token',
            field=models.CharField(blank=True, help_text='Secure token for onboarding link', max_length=255, null=True, unique=True),
        ),
    ]
