# Generated by Django 4.2.30 on 2026-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_alter_caretaker_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caretaker",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="historicalcaretaker",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="historicalrenter",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Renter's email for receipts and notifications",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="renter",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Renter's email for receipts and notifications",
                max_length=254,
            ),
        ),
    ]
