# Generated by Django 4.2.30 on 2026-08-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_alter_caretaker_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrenter",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalrenter",
            name="rated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalrenter",
            name="rating",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="renter",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="renter",
            name="rated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="renter",
            name="rating",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
