# Generated by Django 4.2.30 on 2026-08-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_add_renter_rating_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrenter",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="renter",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
