# Generated by Django 4.2.30 on 2026-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_add_renter_status_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="policeverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("submitted", "Submitted"),
                    ("verified", "Verified"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="policeverification",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policeverification",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
