# Generated by Django 4.2.30 on 2026-08-03 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0008_add_police_verification_status_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ITRCAContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=15),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email address", max_length=254
                    ),
                ),
                ("pan_number", models.CharField(help_text="PAN number", max_length=10)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from the owner",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner who submitted the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ITR CA Contact Request",
                "verbose_name_plural": "ITR CA Contact Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
