# Generated by Django 4.2.30 on 2026-08-03 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0009_add_itr_ca_contact_request_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ITRTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fy_start",
                    models.DateField(
                        help_text="Financial year start date, e.g., 2024-04-01"
                    ),
                ),
                (
                    "fy_end",
                    models.DateField(
                        help_text="Financial year end date, e.g., 2025-03-31"
                    ),
                ),
                (
                    "total_rent_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "ca_review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REVIEWED", "Reviewed"),
                            ("READY", "Ready for Filing"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itr_tracker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ITR Tracker",
                "verbose_name_plural": "ITR Trackers",
                "ordering": ["-fy_start"],
            },
        ),
    ]
