# Generated by Django 4.2.30 on 2026-08-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_add_itr_tracker_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itrtracker",
            name="fy_end",
            field=models.DateField(
                blank=True,
                help_text="Financial year end date, e.g., 2025-03-31",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="itrtracker",
            name="fy_start",
            field=models.DateField(
                blank=True,
                help_text="Financial year start date, e.g., 2024-04-01",
                null=True,
            ),
        ),
    ]
