# Generated by Django 4.2.30 on 2026-08-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_make_itr_tracker_dates_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caretaker",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Currently active?"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcaretaker",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Currently active?"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrenter",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="not_started",
                help_text="KYC verification status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrenter",
            name="notice_start_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalrenter",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Invite"),
                    ("link_sent", "Link Sent"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="pending",
                help_text="Renter self-onboarding progress",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrenter",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("notice_period", "Notice Period"),
                    ("revoked", "Revoked"),
                    ("deactivated", "Deactivated"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrentrecord",
            name="paid_on",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date when payment was made",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrentrecord",
            name="payout_status",
            field=models.CharField(
                db_index=True,
                default="PENDING",
                help_text="Payout transfer status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrentrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                help_text="Payment status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="policeverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("submitted", "Submitted"),
                    ("verified", "Verified"),
                ],
                db_index=True,
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="propertytaxrecord",
            name="due_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="propertytaxrecord",
            name="paid",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="propertytaxrecord",
            name="paid_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="renter",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="not_started",
                help_text="KYC verification status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="renter",
            name="notice_start_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="renter",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Invite"),
                    ("link_sent", "Link Sent"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="pending",
                help_text="Renter self-onboarding progress",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="renter",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("notice_period", "Notice Period"),
                    ("revoked", "Revoked"),
                    ("deactivated", "Deactivated"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rentrecord",
            name="paid_on",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date when payment was made",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rentrecord",
            name="payout_status",
            field=models.CharField(
                db_index=True,
                default="PENDING",
                help_text="Payout transfer status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rentrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                help_text="Payment status",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="extracharge",
            index=models.Index(
                fields=["unit", "status"], name="properties__unit_id_e5387d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extracharge",
            index=models.Index(
                fields=["renter", "status"], name="properties__renter__dd4c31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertytaxrecord",
            index=models.Index(
                fields=["property", "paid", "due_date"],
                name="properties__propert_d8c628_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="renter",
            index=models.Index(
                fields=["unit", "status"], name="properties__unit_id_928347_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="renter",
            index=models.Index(
                fields=["unit", "is_active"], name="properties__unit_id_5a0c26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentrecord",
            index=models.Index(
                fields=["unit", "status", "due_date"],
                name="properties__unit_id_e28254_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentrecord",
            index=models.Index(
                fields=["unit", "payout_status"], name="properties__unit_id_781bc4_idx"
            ),
        ),
    ]
