# Generated by Django 4.2 on 2026-06-26
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workflow_file", models.CharField(db_index=True, max_length=255)),
                ("workflow_name", models.CharField(blank=True, max_length=255)),
                ("triggered_by", models.CharField(default="manual", max_length=255)),
                (
                    "trigger_event",
                    models.CharField(default="workflow_dispatch", max_length=50),
                ),
                ("branch", models.CharField(blank=True, db_index=True, max_length=255)),
                ("commit_sha", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("conclusion", models.CharField(blank=True, max_length=50)),
                ("jobs_total", models.IntegerField(default=0)),
                ("jobs_completed", models.IntegerField(default=0)),
                ("jobs_failed", models.IntegerField(default=0)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="ci_dashboard_status_created_idx",
                    ),
                    models.Index(
                        fields=["workflow_file", "created_at"],
                        name="ci_dashboard_workflow_created_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("runner_label", models.CharField(blank=True, max_length=255)),
                ("needs", models.JSONField(blank=True, default=list)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="ci_dashboard.workflowrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow_run", "status"],
                        name="ci_dashboard_workflow_status_idx",
                    ),
                    models.Index(
                        fields=["job_id", "workflow_run"],
                        name="ci_dashboard_job_workflow_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StepRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("command", models.TextField(blank=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="ci_dashboard.jobrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_run", "status"], name="ci_dashboard_job_status_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                (
                    "stream",
                    models.CharField(
                        choices=[
                            ("stdout", "Stdout"),
                            ("stderr", "Stderr"),
                            ("system", "System"),
                        ],
                        default="stdout",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("run_number", models.IntegerField(default=1)),
                (
                    "job_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="ci_dashboard.jobrun",
                    ),
                ),
                (
                    "step_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="ci_dashboard.steprun",
                    ),
                ),
                (
                    "workflow_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="ci_dashboard.workflowrun",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["workflow_run", "timestamp"],
                        name="ci_dashboard_wf_run_ts_idx",
                    ),
                    models.Index(
                        fields=["job_run", "timestamp"],
                        name="ci_dashboard_job_run_ts_idx",
                    ),
                    models.Index(
                        fields=["step_run", "timestamp"],
                        name="ci_dashboard_step_run_ts_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("workflow_name", models.CharField(max_length=255)),
                ("raw_yaml", models.TextField()),
                ("parsed_json", models.JSONField(blank=True, default=dict)),
                ("jobs", models.JSONField(blank=True, default=dict)),
                ("on_trigger", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["workflow_name"],
            },
        ),
    ]
