# Generated by Django 4.2.30 on 2026-06-26 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ci_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="jobrun",
            new_name="ci_dashboar_workflo_da9ef5_idx",
            old_name="ci_dashboard_workflow_status_idx",
        ),
        migrations.RenameIndex(
            model_name="jobrun",
            new_name="ci_dashboar_job_id_3f9b08_idx",
            old_name="ci_dashboard_job_workflow_idx",
        ),
        migrations.RenameIndex(
            model_name="logentry",
            new_name="ci_dashboar_workflo_073d03_idx",
            old_name="ci_dashboard_wf_run_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="logentry",
            new_name="ci_dashboar_job_run_3ef2d1_idx",
            old_name="ci_dashboard_job_run_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="logentry",
            new_name="ci_dashboar_step_ru_4e1c07_idx",
            old_name="ci_dashboard_step_run_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="steprun",
            new_name="ci_dashboar_job_run_00484a_idx",
            old_name="ci_dashboard_job_status_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowrun",
            new_name="ci_dashboar_status_8b71e6_idx",
            old_name="ci_dashboard_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowrun",
            new_name="ci_dashboar_workflo_d822d9_idx",
            old_name="ci_dashboard_workflow_created_idx",
        ),
        migrations.AlterField(
            model_name="logentry",
            name="job_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_entries",
                to="ci_dashboard.jobrun",
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="step_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_entries",
                to="ci_dashboard.steprun",
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="workflow_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_entries",
                to="ci_dashboard.workflowrun",
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="jobs",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="on_trigger",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="parsed_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name="workflowrun",
            index=models.Index(
                fields=["branch", "created_at"], name="ci_dashboar_branch_339b8d_idx"
            ),
        ),
    ]
