from typing import Any, Protocol


class NotificationChannel(Protocol):
    def send_whatsapp_message(self, phone: str, text: str) -> bool: ...

    def send_whatsapp_audio(self, phone: str, audio_path: str) -> bool: ...

    def send_sms(self, phone: str, message: str) -> bool: ...

    def send_push_notification(
        self, user: Any, title: str, message: str
    ) -> bool | None: ...

    def generate_voice_note(self, text: str, lang: str) -> str: ...
