from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

REPORT_HEADER = "# Branch Protection Validation Report"
REPORT_FOOTER = "---\n*Generated by branch protection validator.*"

JSON_REPORT_NAME = "branch-protection-report.json"
REPORT_NAME = "branch-protection-report.txt"

DEFAULT_REQUIRED_CHECKS = [
    "lint-fast",
    "test-shard-1",
    "test-shard-2",
    "test-shard-3",
    "test-shard-4",
    "shard-validation",
    "contract-tests",
    "architecture",
    "security-fast",
    "quality",
    "deploy-readiness",
]

REQUIRED_REVIEWS_MIN = 2

_SECRET_SCANNING = "secret_scanning"  # noqa: S105

REQUIRED_WORKFLOWS = [
    ".github/workflows/ci.yml",
    ".github/workflows/lint.yml",
    ".github/workflows/test.yml",
    ".github/workflows/security.yml",
    ".github/workflows/security-deep.yml",
    ".github/workflows/quality.yml",
    ".github/workflows/architecture.yml",
    ".github/workflows/contract-tests.yml",
    ".github/workflows/django-check.yml",
    ".github/workflows/deploy-readiness.yml",
    ".github/workflows/deploy.yml",
    ".github/workflows/branch-protection-validator.yml",
    ".github/workflows/nightly.yml",
    ".github/workflows/weekly.yml",
    ".github/workflows/architecture-guard.yml",
    ".github/workflows/benchmark.yml",
    ".github/workflows/load-test.yml",
    ".github/workflows/runtime-measurement.yml",
    ".github/workflows/ci-metrics.yml",
    ".github/workflows/sbom.yml",
    ".github/workflows/rollback.yml",
]

VALIDATOR_VERSION = "2.5.0"
GITHUB_API_VERSION = "2022-11-28"
MAX_RETRIES = 3
RETRY_BACKOFF_FACTOR = 1.0
REQUEST_TIMEOUT = 30
_rate_limit_cache: dict[str, Any] = {
    "remaining": None,
    "reset": None,
    "observed_at": None,
}


def _mask_token(token: str) -> str:
    if not token:
        return ""
    if len(token) <= 8:
        return "***"
    return f"{token[:4]}...{token[-4:]}"


def _create_session() -> Any:
    session = requests.Session()
    retry_strategy = Retry(
        total=MAX_RETRIES,
        backoff_factor=RETRY_BACKOFF_FACTOR,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"],
    )
    adapter = HTTPAdapter(max_retries=retry_strategy)
    session.mount("https://", adapter)
    session.mount("http://", adapter)
    return session


_session = _create_session()


def _get_rate_limit_info(response: Any) -> dict[str, Any]:
    headers = getattr(response, "headers", {}) or {}
    remaining = headers.get("X-RateLimit-Remaining") or headers.get(
        "x-ratelimit-remaining"
    )
    reset = headers.get("X-RateLimit-Reset") or headers.get("x-ratelimit-reset")
    observed_at = datetime.now(UTC).isoformat()
    return {
        "remaining": remaining,
        "reset": reset,
        "observed_at": observed_at,
    }


def _respect_rate_limit(response: Any) -> None:
    global _rate_limit_cache
    info = _get_rate_limit_info(response)
    _rate_limit_cache = info
    if info.get("remaining") == "0" and info.get("reset"):
        try:
            reset_ts = int(info["reset"])
            now = time.time()
            wait = max(0, reset_ts - now) + 1
            if 0 < wait < 60:
                time.sleep(wait)
        except (ValueError, TypeError):
            pass


def api_get(
    url: str, token: str | None, params: dict[str, Any] | None = None
) -> tuple[int, dict[str, Any] | list[Any] | None]:
    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": GITHUB_API_VERSION,
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    try:
        response = _session.get(
            url,
            headers=headers,
            params=params,
            timeout=REQUEST_TIMEOUT,
        )
        _respect_rate_limit(response)
        try:
            data = response.json()
        except ValueError:
            data = {"_error": "Invalid JSON response"}
        return response.status_code, data
    except Exception as exc:  # noqa: BLE001
        return 0, {"_error": str(exc)}


def extract_check_contexts(checks: list[dict[str, Any]]) -> set[str]:
    contexts: set[str] = set()
    for check in checks:
        context = check.get("context")
        if context:
            contexts.add(context)
    return contexts


def get_token() -> str | None:
    gh_token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if gh_token and gh_token.strip():
        return gh_token.strip()
    return None


def get_repo_inputs() -> tuple[str | None, str | None]:
    repo_input = os.environ.get("GITHUB_REPOSITORY")
    if repo_input and "/" in repo_input:
        parts = repo_input.split("/", 1)
        if len(parts) == 2 and parts[0] and parts[1]:
            return parts[0], parts[1]
    return None, None


def classify_protection_status(
    status: int, data: dict[str, Any] | list[Any] | None
) -> tuple[str, str | None]:
    """Classify protection API response into actionable states."""
    if status == 404:
        return "disabled", None
    if status == 403:
        return (
            "unverifiable",
            "Insufficient token permissions to read branch protection",
        )
    if status != 200:
        err = data.get("_error") if isinstance(data, dict) else "unknown error"
        return "unverifiable", f"HTTP {status}: {err}"
    return "enabled", None


def validate_repo_info(owner: str, repo: str, token: str | None) -> dict[str, Any]:
    url = f"https://api.github.com/repos/{owner}/{repo}"
    status, data = api_get(url, token)
    results: dict[str, Any] = {
        "default_branch": None,
        "protected_branches": [],
        "permissions": {},
        "warnings": [],
        "errors": [],
    }
    if status != 200 or not isinstance(data, dict):
        err = data.get("_error") if isinstance(data, dict) else "unknown error"
        results["warnings"].append(f"Could not fetch repo info: HTTP {status} - {err}")
        return results

    results["default_branch"] = data.get("default_branch")
    protection = data.get("branch_protection")
    if isinstance(protection, list):
        results["protected_branches"] = [
            b.get("name") for b in protection if isinstance(b, dict) and b.get("name")
        ]
    permissions = data.get("permissions")
    if isinstance(permissions, dict):
        results["permissions"] = permissions
    return results


def validate_branch_protection(
    owner: str, repo: str, branch: str, token: str | None
) -> dict[str, Any]:
    url = f"https://api.github.com/repos/{owner}/{repo}/branches/{branch}/protection"
    status, data = api_get(url, token)
    results: dict[str, Any] = {
        "branch": branch,
        "status": "unknown",
        "exists": False,
        "checks": {},
        "warnings": [],
        "errors": [],
        "http_status": status,
    }
    protection_state, note = classify_protection_status(status, data)
    results["status"] = protection_state
    if note:
        results["warnings"].append(note)
        return results

    results["exists"] = True
    required_status_checks = (
        data.get("required_status_checks", {}) if isinstance(data, dict) else {}
    )
    checks = (
        required_status_checks.get("checks", [])
        if isinstance(required_status_checks, dict)
        else []
    )
    results["checks"]["contexts"] = sorted(extract_check_contexts(checks))
    results["checks"]["strict"] = (
        required_status_checks.get("strict", False)
        if isinstance(required_status_checks, dict)
        else False
    )
    results["checks"]["required_approving_review_count"] = None
    results["checks"]["dismiss_stale_reviews"] = False
    results["checks"]["require_code_owner_reviews"] = False
    results["checks"]["require_last_push_approval"] = False
    enforce_admins = data.get("enforce_admins", {}) if isinstance(data, dict) else {}
    results["checks"]["enforce_admins"] = (
        enforce_admins.get("enabled", False)
        if isinstance(enforce_admins, dict)
        else False
    )
    allow_force_pushes = (
        data.get("allow_force_pushes", {}) if isinstance(data, dict) else {}
    )
    results["checks"]["allow_force_pushes"] = (
        allow_force_pushes.get("enabled", False)
        if isinstance(allow_force_pushes, dict)
        else False
    )
    allow_deletions = data.get("allow_deletions", {}) if isinstance(data, dict) else {}
    results["checks"]["allow_deletions"] = (
        allow_deletions.get("enabled", False)
        if isinstance(allow_deletions, dict)
        else False
    )
    required_pull_request_reviews = (
        data.get("required_pull_request_reviews", {}) if isinstance(data, dict) else {}
    )
    if isinstance(required_pull_request_reviews, dict):
        results["checks"]["required_approving_review_count"] = (
            required_pull_request_reviews.get("required_approving_review_count")
        )
        results["checks"]["dismiss_stale_reviews"] = required_pull_request_reviews.get(
            "dismiss_stale_reviews", False
        )
        results["checks"]["require_code_owner_reviews"] = (
            required_pull_request_reviews.get("require_code_owner_reviews", False)
        )
        results["checks"]["require_last_push_approval"] = (
            required_pull_request_reviews.get("require_last_push_approval", False)
        )
    required_linear_history = (
        data.get("required_linear_history", {}) if isinstance(data, dict) else {}
    )
    results["checks"]["required_linear_history"] = (
        required_linear_history.get("enabled", False)
        if isinstance(required_linear_history, dict)
        else False
    )
    required_conversation_resolution = (
        data.get("required_conversation_resolution", {})
        if isinstance(data, dict)
        else {}
    )
    results["checks"]["required_conversation_resolution"] = (
        required_conversation_resolution.get("enabled", False)
        if isinstance(required_conversation_resolution, dict)
        else False
    )
    commit_signing_required = (
        data.get("commit_signing_required", {}) if isinstance(data, dict) else {}
    )
    results["checks"]["commit_signing_required"] = (
        commit_signing_required.get("enabled", False)
        if isinstance(commit_signing_required, dict)
        else False
    )
    allowed_merge_methods = (
        data.get("allowed_merge_methods", {}) if isinstance(data, dict) else {}
    )
    results["checks"]["allowed_merge_methods"] = (
        allowed_merge_methods.get("allowed", [])
        if isinstance(allowed_merge_methods, dict)
        else []
    )
    return results


def validate_rulesets(owner: str, repo: str, token: str | None) -> dict[str, Any]:
    url = f"https://api.github.com/repos/{owner}/{repo}/rulesets"
    status, data = api_get(url, token)
    results: dict[str, Any] = {
        "count": 0,
        "rulesets": [],
        "status": "unknown",
        "warnings": [],
        "errors": [],
    }
    if status == 404:
        results["status"] = "disabled"
        results["warnings"].append("No rulesets configured")
        return results
    if status == 403:
        results["status"] = "unverifiable"
        results["warnings"].append("Insufficient token permissions to read rulesets")
        return results
    if status != 200 or not isinstance(data, list):
        err = data.get("_error") if isinstance(data, dict) else "unknown error"
        results["status"] = "unverifiable"
        results["warnings"].append(f"Could not fetch rulesets: HTTP {status} - {err}")
        return results
    results["status"] = "enabled"
    results["count"] = len(data)
    results["rulesets"] = [
        {
            "id": r.get("id"),
            "name": r.get("name"),
            "target": r.get("target"),
            "enforcement": r.get("enforcement"),
        }
        for r in data
        if isinstance(r, dict)
    ]
    return results


def validate_workflow_integrity(
    owner: str, repo: str, token: str | None
) -> dict[str, Any]:
    workspace = os.environ.get("GITHUB_WORKSPACE") or os.getcwd()
    results: dict[str, Any] = {"missing": [], "warnings": [], "errors": []}
    for workflow in REQUIRED_WORKFLOWS:
        path = os.path.join(workspace, workflow)
        if not os.path.exists(path):
            results["missing"].append(workflow)
    if results["missing"]:
        results["errors"].append(
            f"Missing critical workflows: {', '.join(results['missing'])}"
        )
    return results


def validate_workflow_security(
    owner: str, repo: str, token: str | None
) -> dict[str, Any]:
    results: dict[str, Any] = {"findings": [], "warnings": [], "status": "unknown"}
    repo_url = f"https://api.github.com/repos/{owner}/{repo}"
    status, data = api_get(repo_url, token)
    if status == 200 and isinstance(data, dict):
        results["status"] = "verified"
        default_branch = data.get("default_branch")
        if default_branch:
            results["default_branch"] = default_branch
    else:
        results["warnings"].append(
            "Could not fetch repository metadata for workflow security audit"
        )
    return results


def validate_merge_queue(protection: dict[str, Any]) -> dict[str, Any]:
    allow_force_pushes_bypass = protection.get("checks", {}).get(
        "allow_force_pushes_bypass", {}
    )
    if isinstance(allow_force_pushes_bypass, dict):
        enabled = allow_force_pushes_bypass.get("enabled", False)
        return {"enabled": enabled, "warning": None}
    return {"enabled": False, "warning": "Merge queue configuration unavailable"}


def _render_permissions_audit(repo_info: dict[str, Any]) -> list[str]:
    lines = ["## Permissions Audit", ""]
    permissions = repo_info.get("permissions", {})
    if permissions:
        readable = ", ".join(sorted(permissions.keys())) or "none"
        lines.append(f"- Repository permissions visible to token: `{readable}`")
    else:
        lines.append("- Repository permissions visible to token: `unknown`")
    lines.append(
        "- If branch protection or rulesets show as `unverifiable`, re-run with"
        " a PAT having `administration` and `rulesets` scope."
    )
    lines.append("")
    return lines


def _render_single_branch_protection(  # noqa: C901
    branch_name: str,
    protection: dict[str, Any],
    required_checks: list[str],
) -> tuple[list[str], int, int, int]:
    lines: list[str] = []
    critical_delta = 0
    score_delta = 0
    warning_delta = 0
    protection_state = protection.get("status", "unknown")

    if protection_state == "unverifiable":
        reason = protection.get("warnings", ["unknown"])[0]
        lines.append(f"- **{branch_name}**: ⚠️ Unable to verify — {reason}")
        warning_delta += 1
        return lines, critical_delta, score_delta, warning_delta

    if not protection.get("exists"):
        lines.append(f"- **{branch_name}**: ❌ FAIL — Branch protection is not enabled")
        critical_delta += 1
        score_delta -= 25
        return lines, critical_delta, score_delta, warning_delta

    lines.append(f"- **{branch_name}**: ✅ Enabled")
    contexts = protection.get("checks", {}).get("contexts", [])
    missing = [c for c in required_checks if c not in contexts]
    if missing:
        lines.append(f"  - Required checks: ❌ Missing: {', '.join(missing)}")
        critical_delta += 1
        score_delta -= 15
    else:
        lines.append(
            f"  - Required checks: ✅ All {len(required_checks)} checks present"
        )
    checks = protection.get("checks", {})
    if checks.get("allow_force_pushes"):
        lines.append("  - Force push: ❌ FAIL — Force push is enabled")
        critical_delta += 1
        score_delta -= 15
    else:
        lines.append("  - Force push: ✅ Disabled")
    if checks.get("allow_deletions"):
        lines.append("  - Branch deletion: ❌ FAIL — Branch deletion is enabled")
        critical_delta += 1
        score_delta -= 15
    else:
        lines.append("  - Branch deletion: ✅ Disabled")
    if checks.get("enforce_admins"):
        lines.append("  - Admin enforcement: ✅ Admins must obey rules")
    else:
        lines.append("  - Admin enforcement: ❌ FAIL — Admins can bypass")
        critical_delta += 1
        score_delta -= 10
    if checks.get("required_conversation_resolution"):
        lines.append("  - Conversation resolution: ✅ Required")
    else:
        lines.append("  - Conversation resolution: ⚠️ Not required")
        warning_delta += 1
    approve_count = checks.get("required_approving_review_count")
    if approve_count and approve_count >= REQUIRED_REVIEWS_MIN:
        lines.append(f"  - Required reviews: ✅ {approve_count} approvals")
    else:
        actual = approve_count if approve_count is not None else 0
        lines.append(
            f"  - Required reviews: ❌ FAIL — {actual} approvals "
            f"(expected >= {REQUIRED_REVIEWS_MIN})"
        )
        critical_delta += 1
        score_delta -= 10
    if checks.get("dismiss_stale_reviews"):
        lines.append("  - Dismiss stale reviews: ✅ Enabled")
    else:
        lines.append("  - Dismiss stale reviews: ⚠️ Disabled")
        warning_delta += 1
    if checks.get("require_code_owner_reviews"):
        lines.append("  - Code owner reviews: ✅ Required")
    else:
        lines.append("  - Code owner reviews: ⚠️ Not required")
        warning_delta += 1
    if checks.get("required_linear_history"):
        lines.append("  - Linear history: ✅ Required")
    else:
        lines.append("  - Linear history: ⚠️ Not required")
        warning_delta += 1
    allowed = checks.get("allowed_merge_methods", [])
    if allowed:
        lines.append(f"  - Merge methods: {', '.join(allowed)}")
    else:
        lines.append("  - Merge methods: ⚠️ Not configured")
    return lines, critical_delta, score_delta, warning_delta


def _render_branch_protection_section(
    default_protection: dict[str, Any],
    other_protections: dict[str, dict[str, Any]],
    required_checks: list[str],
) -> tuple[list[str], int, int, int]:
    lines: list[str] = ["## Branch Protection"]
    critical_delta = 0
    score_delta = 0
    warning_delta = 0

    for branch_name, protection in [("default", default_protection)] + list(
        other_protections.items()
    ):
        branch_lines, crit, score, warn = _render_single_branch_protection(
            branch_name=branch_name,
            protection=protection,
            required_checks=required_checks,
        )
        lines.extend(branch_lines)
        critical_delta += crit
        score_delta += score
        warning_delta += warn
    lines.append("")
    return lines, critical_delta, score_delta, warning_delta


def _render_merge_queue_section(
    default_protection: dict[str, Any],
) -> tuple[list[str], int]:
    lines: list[str] = ["## Merge Queue"]
    warning_delta = 0
    merge_queue = validate_merge_queue(default_protection)
    if merge_queue.get("enabled"):
        lines.append("- Status: ✅ Enabled")
    else:
        warning = merge_queue.get("warning")
        lines.append(f"- Status: ⚠️ Disabled{f' ({warning})' if warning else ''}")
        warning_delta += 1
    lines.append("")
    return lines, warning_delta


def _render_rulesets_section(rulesets: dict[str, Any]) -> tuple[list[str], int]:
    lines: list[str] = ["## Rulesets"]
    warning_delta = 0
    ruleset_state = rulesets.get("status", "unknown")
    if ruleset_state == "enabled":
        lines.append(f"- Count: {rulesets['count']}")
        for rs in rulesets.get("rulesets", []):
            lines.append(
                f"  - `{rs.get('name')}` ({rs.get('target')}) — {rs.get('enforcement')}"
            )
    elif ruleset_state == "unverifiable":
        warning = rulesets.get("warnings", ["unknown"])[0]
        lines.append(f"- Status: ⚠️ Unable to verify — {warning}")
        warning_delta += 1
    elif ruleset_state == "disabled":
        lines.append("- Status: ⚠️ No rulesets configured")
        warning_delta += 1
    else:
        lines.append("- Status: ⚠️ Unknown")
        warning_delta += 1
    lines.append("")
    return lines, warning_delta


def _render_security_features_section(
    security_features: dict[str, Any],
) -> tuple[list[str], int]:
    lines: list[str] = ["## Security Features"]
    warning_delta = 0
    for feature, value in security_features.items():
        if feature in {"warnings", "errors"}:
            continue
        display = value.replace("_", " ").title()
        if value in {"enabled", "available"}:
            lines.append(f"- {display}: ✅ {value.title()}")
        elif value in {"disabled"}:
            lines.append(f"- {display}: ⚠️ Disabled")
            warning_delta += 1
        elif value in {"unverifiable"}:
            reason = security_features.get("warnings", [""])[0]
            lines.append(f"- {display}: ⚠️ Unable to verify — {reason}")
            warning_delta += 1
        else:
            lines.append(f"- {display}: ⚠️ Unable to verify")
            warning_delta += 1
    lines.append("")
    return lines, warning_delta


def _render_workflow_security_section(
    workflow_security: dict[str, Any],
) -> tuple[list[str], int]:
    lines: list[str] = ["## Workflow Security"]
    warning_delta = 0
    if workflow_security.get("findings"):
        for finding in workflow_security.get("findings", []):
            lines.append(f"- ❌ {finding}")
            warning_delta += 1
    elif workflow_security.get("warnings"):
        for warning in workflow_security.get("warnings", []):
            lines.append(f"- ⚠️ {warning}")
            warning_delta += 1
    else:
        lines.append("- ✅ No dangerous workflow permissions detected")
    lines.append("")
    return lines, warning_delta


def _render_workflow_integrity_section(
    workflow_integrity: dict[str, Any],
) -> tuple[list[str], int, int]:
    lines: list[str] = ["## Workflow Integrity"]
    critical_delta = 0
    score_delta = 0
    if workflow_integrity.get("missing"):
        lines.append(
            f"- ❌ Missing workflows: {', '.join(workflow_integrity['missing'])}"
        )
        critical_delta += 1
        score_delta -= 20
    else:
        lines.append("- ✅ All critical workflows present")
    lines.append("")
    return lines, critical_delta, score_delta


def _render_overall_section(
    overall_score: int, critical_failures: int, warning_count: int
) -> list[str]:
    lines: list[str] = ["## Overall Score"]
    lines.append(f"Score: {overall_score}/100")
    if critical_failures > 0:
        lines.append(f"Status: ❌ FAIL — {critical_failures} critical failure(s)")
    else:
        lines.append(f"Status: ✅ PASS — {warning_count} warning(s)")
    lines.append("")
    lines.append(REPORT_FOOTER)
    return lines


def validate_security_features(  # noqa: C901
    owner: str, repo: str, token: str | None
) -> dict[str, Any]:
    results: dict[str, Any] = {
        "dependency_review": "unknown",
        "codeql": "unknown",
        _SECRET_SCANNING: "unknown",
        "push_protection": "unknown",
        "dependabot_alerts": "unknown",
        "dependabot_security_updates": "unknown",
        "sbom": "unknown",
        "artifact_attestations": "unknown",
        "oidc": "unknown",
        "warnings": [],
        "errors": [],
    }
    dep_review_url = (
        f"https://api.github.com/repos/{owner}/{repo}/dependency-graph/snapshots"
    )
    status, _ = api_get(dep_review_url, token)
    if status == 200:
        results["dependency_review"] = "available"
    elif status == 403:
        results["dependency_review"] = "unverifiable"
        results["warnings"].append(
            "Insufficient token permissions to read dependency graph"
        )
    else:
        results["dependency_review"] = "unavailable"

    codeql_url = f"https://api.github.com/repos/{owner}/{repo}/code-scanning/setup"
    status, data = api_get(codeql_url, token)
    if status == 200 and isinstance(data, dict):
        results["codeql"] = "enabled"
    elif status == 404:
        results["codeql"] = "disabled"
    elif status == 403:
        results["codeql"] = "unverifiable"
        results["warnings"].append(
            "Insufficient token permissions to read CodeQL setup"
        )
    else:
        results["codeql"] = "unknown"

    ss_url = f"https://api.github.com/repos/{owner}/{repo}/secret-scanning"
    status, data = api_get(ss_url, token)
    if status == 200 and isinstance(data, dict):
        results[_SECRET_SCANNING] = "enabled"
        results["push_protection"] = (
            "enabled" if data.get("push_protection_enabled") else "disabled"
        )
    elif status == 404:
        results[_SECRET_SCANNING] = "disabled"
        results["push_protection"] = "disabled"
    elif status == 403:
        results[_SECRET_SCANNING] = "unverifiable"
        results["push_protection"] = "unverifiable"
        results["warnings"].append(
            "Insufficient token permissions to read secret scanning"
        )
    else:
        results[_SECRET_SCANNING] = "unknown"
        results["push_protection"] = "unknown"
        results["warnings"].append(f"Secret Scanning API returned HTTP {status}")

    da_url = f"https://api.github.com/repos/{owner}/{repo}/dependabot/alerts"
    status, _ = api_get(da_url, token)
    if status == 200:
        results["dependabot_alerts"] = "enabled"
    elif status == 403:
        results["dependabot_alerts"] = "unverifiable"
        results["warnings"].append(
            "Insufficient token permissions to read Dependabot alerts"
        )
    else:
        results["dependabot_alerts"] = "disabled_or_unavailable"

    dsu_url = f"https://api.github.com/repos/{owner}/{repo}/dependabot/updates"
    status, data = api_get(dsu_url, token)
    if status == 200 and isinstance(data, list):
        results["dependabot_security_updates"] = "enabled"
    elif status == 403:
        results["dependabot_security_updates"] = "unverifiable"
    else:
        results["dependabot_security_updates"] = "disabled_or_unavailable"

    sbom_url = f"https://api.github.com/repos/{owner}/{repo}/sbom"
    status, _ = api_get(sbom_url, token)
    if status == 200:
        results["sbom"] = "available"
    elif status == 403:
        results["sbom"] = "unverifiable"
    else:
        results["sbom"] = "unavailable"

    att_url = f"https://api.github.com/repos/{owner}/{repo}/attestations"
    status, _ = api_get(att_url, token)
    if status == 200:
        results["artifact_attestations"] = "available"
    elif status == 403:
        results["artifact_attestations"] = "unverifiable"
    else:
        results["artifact_attestations"] = "unavailable"

    oidc_url = f"https://api.github.com/repos/{owner}/{repo}/actions/oidc"
    status, _ = api_get(oidc_url, token)
    if status == 200:
        results["oidc"] = "available"
    elif status == 403:
        results["oidc"] = "unverifiable"
    else:
        results["oidc"] = "unavailable"

    return results


def build_report(
    owner: str,
    repo: str,
    default_protection: dict[str, Any],
    other_protections: dict[str, dict[str, Any]],
    repo_info: dict[str, Any],
    rulesets: dict[str, Any],
    workflow_integrity: dict[str, Any],
    security_features: dict[str, Any],
    workflow_security: dict[str, Any],
    required_checks: list[str],
    execution_duration: float | None = None,
) -> str:
    lines: list[str] = [REPORT_HEADER, ""]
    lines.append(f"Repository: `{owner}/{repo}`")
    lines.append(f"Default branch: `{repo_info.get('default_branch') or 'unknown'}`")
    protected = repo_info.get("protected_branches", [])
    if protected:
        lines.append(f"Protected branches: `{', '.join(protected)}`")
    else:
        lines.append("Protected branches: `none detected from repo metadata`")
    lines.append("")
    overall_score = 100
    critical_failures = 0
    warning_count = 0

    section_lines, crit_delta, score_delta, warn_delta = (
        _render_branch_protection_section(
            default_protection=default_protection,
            other_protections=other_protections,
            required_checks=required_checks,
        )
    )
    lines.extend(section_lines)
    critical_failures += crit_delta
    overall_score += score_delta
    warning_count += warn_delta

    section_lines, warn_delta = _render_merge_queue_section(
        default_protection=default_protection,
    )
    lines.extend(section_lines)
    warning_count += warn_delta

    section_lines, warn_delta = _render_rulesets_section(rulesets=rulesets)
    lines.extend(section_lines)
    warning_count += warn_delta

    section_lines, warn_delta = _render_security_features_section(
        security_features=security_features,
    )
    lines.extend(section_lines)
    warning_count += warn_delta

    section_lines, warn_delta = _render_workflow_security_section(
        workflow_security=workflow_security,
    )
    lines.extend(section_lines)
    warning_count += warn_delta

    lines.extend(_render_permissions_audit(repo_info=repo_info))

    section_lines, crit_delta, score_delta = _render_workflow_integrity_section(
        workflow_integrity=workflow_integrity,
    )
    lines.extend(section_lines)
    critical_failures += crit_delta
    overall_score += score_delta

    if execution_duration is not None:
        lines.append("## Execution Metrics")
        lines.append(f"- Duration: {execution_duration:.2f}s")
        remaining = _rate_limit_cache.get("remaining") or "unknown"
        observed_at = _rate_limit_cache.get("observed_at") or "unknown"
        lines.append(f"- Rate limit remaining: {remaining}")
        lines.append(f"- Rate limit observed at: {observed_at}")
        lines.append("")

    lines.extend(
        _render_overall_section(
            overall_score=overall_score,
            critical_failures=critical_failures,
            warning_count=warning_count,
        )
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Branch Protection Validator")
    parser.add_argument("--json", action="store_true", help="Output report as JSON")
    parser.add_argument("--token", help="GitHub token override")
    parser.add_argument("--repo", help="Repository override (owner/repo)")
    parser.add_argument(
        "--required-checks", help="Comma-separated required check names"
    )
    parser.add_argument(
        "--output-dir",
        default=".",
        help="Directory to write report artifacts",
    )
    args = parser.parse_args()

    token = args.token or get_token()
    if not token:
        print("SKIPPED: GITHUB_TOKEN or GH_TOKEN is not available.")
        return 0

    owner, repo = None, None
    if args.repo and "/" in args.repo:
        owner, repo = args.repo.split("/", 1)
    else:
        owner, repo = get_repo_inputs()

    if not owner or not repo:
        print("SKIPPED: Repository could not be determined.")
        return 0

    required_checks = DEFAULT_REQUIRED_CHECKS
    if args.required_checks:
        required_checks = [
            c.strip() for c in args.required_checks.split(",") if c.strip()
        ]

    started_at = time.time()
    repo_info = validate_repo_info(owner, repo, token)
    default_branch = repo_info.get("default_branch")
    protected_branches = repo_info.get("protected_branches", [])

    default_protection: dict[str, Any] = {"status": "unknown", "exists": False}
    if default_branch:
        default_protection = validate_branch_protection(
            owner, repo, default_branch, token
        )

    other_protections: dict[str, dict[str, Any]] = {}
    for branch in protected_branches:
        if branch == default_branch:
            continue
        other_protections[branch] = validate_branch_protection(
            owner, repo, branch, token
        )

    rulesets = validate_rulesets(owner, repo, token)
    workflow_integrity = validate_workflow_integrity(owner, repo, token)
    security_features = validate_security_features(owner, repo, token)
    workflow_security = validate_workflow_security(owner, repo, token)
    execution_duration = time.time() - started_at

    if args.json:
        payload = _build_json_payload(
            owner=owner,
            repo=repo,
            token=token,
            default_branch=default_branch,
            default_protection=default_protection,
            other_protections=other_protections,
            repo_info=repo_info,
            rulesets=rulesets,
            workflow_integrity=workflow_integrity,
            security_features=security_features,
            workflow_security=workflow_security,
            execution_duration=execution_duration,
        )
        print(json.dumps(payload, indent=2, default=str))
        return 0

    report = build_report(
        owner=owner,
        repo=repo,
        default_protection=default_protection,
        other_protections=other_protections,
        repo_info=repo_info,
        rulesets=rulesets,
        workflow_integrity=workflow_integrity,
        security_features=security_features,
        workflow_security=workflow_security,
        required_checks=required_checks,
        execution_duration=execution_duration,
    )
    print(report)

    _write_reports(
        args.output_dir,
        owner,
        repo,
        token,
        default_branch,
        default_protection,
        other_protections,
        repo_info,
        rulesets,
        workflow_integrity,
        security_features,
        workflow_security,
        execution_duration,
        report,
    )

    critical_failures = _count_critical_failures(
        default_protection, other_protections, workflow_integrity
    )
    return 1 if critical_failures > 0 else 0


def _build_json_payload(
    owner: str,
    repo: str,
    token: str,
    default_branch: str | None,
    default_protection: dict[str, Any],
    other_protections: dict[str, dict[str, Any]],
    repo_info: dict[str, Any],
    rulesets: dict[str, Any],
    workflow_integrity: dict[str, Any],
    security_features: dict[str, Any],
    workflow_security: dict[str, Any],
    execution_duration: float,
) -> dict[str, Any]:
    summary_parts = []
    for protection in [default_protection, *other_protections.values()]:
        summary_parts.extend(protection.get("errors", []))
    summary_parts.extend(workflow_integrity.get("errors", []))
    critical_failures = sum(
        1
        for message in summary_parts
        if "not enabled" in message or "Missing" in message
    )
    warning_count = sum(
        1
        for protection in [default_protection, *other_protections.values()]
        for message in protection.get("warnings", [])
    )
    warning_count += len(rulesets.get("warnings", []))
    warning_count += len(security_features.get("warnings", []))
    warning_count += len(workflow_security.get("warnings", []))
    status = "FAIL" if critical_failures > 0 else "PASS"
    return {
        "version": VALIDATOR_VERSION,
        "timestamp": datetime.now(UTC).isoformat(),
        "repository": f"{owner}/{repo}",
        "default_branch": default_branch,
        "score": max(
            0,
            100
            + sum(
                protection.get("score_delta", 0)
                for protection in [default_protection, *other_protections.values()]
            ),
        ),
        "status": status,
        "execution_duration_seconds": round(execution_duration, 3),
        "token": {
            "type": "GITHUB_TOKEN" if not os.environ.get("GH_TOKEN") else "GH_TOKEN",
            "masked": _mask_token(token),
            "permissions_visible": list(repo_info.get("permissions", {}).keys()),
        },
        "rate_limit": {
            key: value for key, value in _rate_limit_cache.items() if value is not None
        },
        "validations": {
            "branch_protection": {
                "default": default_protection,
                "other": other_protections,
            },
            "rulesets": {
                "count": rulesets.get("count", 0),
                "status": rulesets.get("status", "unknown"),
                "items": rulesets.get("rulesets", []),
            },
            "security_features": {
                key: value
                for key, value in security_features.items()
                if key not in {"warnings", "errors"}
            },
            "workflow_security": workflow_security.get("findings", []),
            "workflow_integrity": {
                "missing": workflow_integrity.get("missing", []),
                "errors": workflow_integrity.get("errors", []),
            },
        },
        "summary": {
            "critical_failures": critical_failures,
            "warning_count": warning_count,
            "execution_duration_seconds": round(execution_duration, 3),
        },
        "api_endpoint_states": {
            "repo_info": "ok" if repo_info.get("default_branch") else "unverifiable",
            "rulesets": rulesets.get("status", "unknown"),
            "security_features": {
                key: value
                for key, value in security_features.items()
                if key not in {"warnings", "errors"}
            },
        },
    }


def _write_reports(
    output_dir: str,
    owner: str,
    repo: str,
    token: str,
    default_branch: str | None,
    default_protection: dict[str, Any],
    other_protections: dict[str, dict[str, Any]],
    repo_info: dict[str, Any],
    rulesets: dict[str, Any],
    workflow_integrity: dict[str, Any],
    security_features: dict[str, Any],
    workflow_security: dict[str, Any],
    execution_duration: float,
    report: str,
) -> None:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    json_payload = _build_json_payload(
        owner=owner,
        repo=repo,
        token=token,
        default_branch=default_branch,
        default_protection=default_protection,
        other_protections=other_protections,
        repo_info=repo_info,
        rulesets=rulesets,
        workflow_integrity=workflow_integrity,
        security_features=security_features,
        workflow_security=workflow_security,
        execution_duration=execution_duration,
    )
    report_text = json.dumps(json_payload, indent=2, default=str)
    _atomic_write(out / JSON_REPORT_NAME, report_text)
    _atomic_write(out / REPORT_NAME, report)


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp-", suffix=path.suffix)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.replace(tmp, str(path))
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _count_critical_failures(
    default_protection: dict[str, Any],
    other_protections: dict[str, dict[str, Any]],
    workflow_integrity: dict[str, Any],
) -> int:
    failures = 0
    for protection in [default_protection, *other_protections.values()]:
        if protection.get("status") == "unverifiable":
            continue
        failures += sum(
            1
            for e in protection.get("errors", [])
            if "not enabled" in e or "Missing" in e
        )
    failures += len(workflow_integrity.get("errors", []))
    return failures


if __name__ == "__main__":
    sys.exit(main())
