#!/usr/bin/env python3
"""
Branch Protection Validator
Enterprise-grade auditor for GitHub branch protection and repository security settings.

Read-only audit. Never modifies repository settings.
Fails only on critical security drift.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any

try:
    import requests
except ImportError:
    requests = None  # type: ignore[assignment]

REPORT_HEADER = "# Branch Protection Validation Report"
REPORT_FOOTER = "---\n*Generated by branch protection validator.*"

DEFAULT_REQUIRED_CHECKS = [
    "lint-fast",
    "test-shard-1",
    "test-shard-2",
    "test-shard-3",
    "test-shard-4",
    "shard-validation",
    "contract-tests",
    "architecture",
    "security-fast",
    "quality",
    "deploy-readiness",
]

REQUIRED_REVIEWS_MIN = 2

_SECRET_SCANNING = "secret_scanning"  # noqa: S105


def get_token() -> str | None:
    gh_token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if gh_token and gh_token.strip():
        return gh_token.strip()
    return None


def get_repo_info() -> tuple[str, str] | None:
    github_repository = os.environ.get("GITHUB_REPOSITORY")
    if github_repository and "/" in github_repository:
        parts = github_repository.split("/", 1)
        if len(parts) == 2 and parts[0] and parts[1]:
            return parts[0], parts[1]
    return None


def api_get(
    url: str, token: str | None, params: dict[str, Any] | None = None
) -> tuple[int, dict[str, Any] | list[Any] | None]:
    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    try:
        response = requests.get(url, headers=headers, params=params, timeout=30)
        return response.status_code, response.json()
    except Exception as exc:  # noqa: BLE001
        return 0, {"_error": str(exc)}


def extract_check_contexts(checks: list[dict[str, Any]]) -> set[str]:
    contexts: set[str] = set()
    for check in checks:
        context = check.get("context")
        if context:
            contexts.add(context)
    return contexts


def validate_branch_protection(
    owner: str, repo: str, branch: str, token: str | None
) -> dict[str, Any]:
    url = f"https://api.github.com/repos/{owner}/{repo}/branches/{branch}/protection"
    status, data = api_get(url, token)
    results: dict[str, Any] = {
        "branch": branch,
        "exists": False,
        "checks": {},
        "warnings": [],
        "errors": [],
    }
    if status == 404:
        results["errors"].append(f"Branch protection is not enabled on {branch}")
        return results
    if status != 200:
        err = data.get("_error") if isinstance(data, dict) else "unknown error"
        results["warnings"].append(
            f"Could not fetch branch protection for {branch}: HTTP {status} - {err}"
        )
        return results
    results["exists"] = True
    required_status_checks = (
        data.get("required_status_checks", {}) if isinstance(data, dict) else {}
    )
    checks = (
        required_status_checks.get("checks", [])
        if isinstance(required_status_checks, dict)
        else []
    )
    results["checks"]["contexts"] = sorted(extract_check_contexts(checks))
    results["checks"]["strict"] = (
        required_status_checks.get("strict", False)
        if isinstance(required_status_checks, dict)
        else False
    )
    enforce_admins = data.get("enforce_admins", {}) if isinstance(data, dict) else {}
    results["checks"]["enforce_admins"] = (
        enforce_admins.get("enabled", False)
        if isinstance(enforce_admins, dict)
        else False
    )
    allow_force_pushes = (
        data.get("allow_force_pushes", {}) if isinstance(data, dict) else {}
    )
    results["checks"]["allow_force_pushes"] = (
        allow_force_pushes.get("enabled", False)
        if isinstance(allow_force_pushes, dict)
        else False
    )
    allow_deletions = data.get("allow_deletions", {}) if isinstance(data, dict) else {}
    results["checks"]["allow_deletions"] = (
        allow_deletions.get("enabled", False)
        if isinstance(allow_deletions, dict)
        else False
    )
    required_pull_request_reviews = (
        data.get("required_pull_request_reviews", {}) if isinstance(data, dict) else {}
    )
    if isinstance(required_pull_request_reviews, dict):
        results["checks"]["required_approving_review_count"] = (
            required_pull_request_reviews.get("required_approving_review_count")
        )
        results["checks"]["dismiss_stale_reviews"] = required_pull_request_reviews.get(
            "dismiss_stale_reviews", False
        )
        results["checks"]["require_code_owner_reviews"] = (
            required_pull_request_reviews.get("require_code_owner_reviews", False)
        )
        results["checks"]["require_last_push_approval"] = (
            required_pull_request_reviews.get("require_last_push_approval", False)
        )
    required_linear_history = (
        data.get("required_linear_history", {}) if isinstance(data, dict) else {}
    )
    results["checks"]["required_linear_history"] = (
        required_linear_history.get("enabled", False)
        if isinstance(required_linear_history, dict)
        else False
    )
    allow_force_pushes_bypass = (
        data.get("allow_force_pushes_bypass", {}) if isinstance(data, dict) else {}
    )
    results["checks"]["allow_force_pushes_bypass"] = (
        allow_force_pushes_bypass.get("enabled", False)
        if isinstance(allow_force_pushes_bypass, dict)
        else False
    )
    required_conversation_resolution = (
        data.get("required_conversation_resolution", {})
        if isinstance(data, dict)
        else {}
    )
    results["checks"]["required_conversation_resolution"] = (
        required_conversation_resolution.get("enabled", False)
        if isinstance(required_conversation_resolution, dict)
        else False
    )
    commit_signing_required = (
        data.get("commit_signing_required", {}) if isinstance(data, dict) else {}
    )
    results["checks"]["commit_signing_required"] = (
        commit_signing_required.get("enabled", False)
        if isinstance(commit_signing_required, dict)
        else False
    )
    allowed_merge_methods = (
        data.get("allowed_merge_methods", {}) if isinstance(data, dict) else {}
    )
    results["checks"]["allowed_merge_methods"] = (
        allowed_merge_methods.get("allowed", [])
        if isinstance(allowed_merge_methods, dict)
        else []
    )
    return results


def validate_rulesets(owner: str, repo: str, token: str | None) -> dict[str, Any]:
    url = f"https://api.github.com/repos/{owner}/{repo}/rulesets"
    status, data = api_get(url, token)
    results: dict[str, Any] = {"count": 0, "rulesets": [], "warnings": [], "errors": []}
    if status == 404 or not isinstance(data, list):
        results["warnings"].append("Rulesets API unavailable or no rulesets configured")
        return results
    results["count"] = len(data)
    results["rulesets"] = [
        {
            "id": r.get("id"),
            "name": r.get("name"),
            "target": r.get("target"),
            "enforcement": r.get("enforcement"),
        }
        for r in data
        if isinstance(r, dict)
    ]
    return results


def validate_repo_info(owner: str, repo: str, token: str | None) -> dict[str, Any]:
    url = f"https://api.github.com/repos/{owner}/{repo}"
    status, data = api_get(url, token)
    results: dict[str, Any] = {"default_branch": None, "warnings": [], "errors": []}
    if status != 200 or not isinstance(data, dict):
        err = data.get("_error") if isinstance(data, dict) else "unknown error"
        results["warnings"].append(f"Could not fetch repo info: HTTP {status} - {err}")
        return results
    results["default_branch"] = data.get("default_branch")
    return results


def validate_workflow_integrity(
    owner: str, repo: str, token: str | None
) -> dict[str, Any]:
    workspace = os.environ.get("GITHUB_WORKSPACE") or os.getcwd()
    required_workflows = [
        ".github/workflows/ci.yml",
        ".github/workflows/lint.yml",
        ".github/workflows/test.yml",
        ".github/workflows/security.yml",
        ".github/workflows/security-deep.yml",
        ".github/workflows/quality.yml",
        ".github/workflows/architecture.yml",
        ".github/workflows/contract-tests.yml",
        ".github/workflows/django-check.yml",
        ".github/workflows/deploy-readiness.yml",
        ".github/workflows/deploy.yml",
        ".github/workflows/branch-protection-validator.yml",
        ".github/workflows/nightly.yml",
        ".github/workflows/weekly.yml",
        ".github/workflows/architecture-guard.yml",
        ".github/workflows/benchmark.yml",
        ".github/workflows/load-test.yml",
        ".github/workflows/runtime-measurement.yml",
        ".github/workflows/ci-metrics.yml",
        ".github/workflows/sbom.yml",
        ".github/workflows/rollback.yml",
    ]
    results: dict[str, Any] = {"missing": [], "warnings": [], "errors": []}
    for workflow in required_workflows:
        path = os.path.join(workspace, workflow)
        if not os.path.exists(path):
            results["missing"].append(workflow)
    if results["missing"]:
        results["errors"].append(
            f"Missing critical workflows: {', '.join(results['missing'])}"
        )
    return results


def validate_security_features(
    owner: str, repo: str, token: str | None
) -> dict[str, Any]:
    results: dict[str, Any] = {
        "dependency_review": "unknown",
        "codeql": "unknown",
        "secret_scanning": "unknown",
        "push_protection": "unknown",
        "dependabot_alerts": "unknown",
        "dependabot_security_updates": "unknown",
        "sbom": "unknown",
        "artifact_attestations": "unknown",
        "oidc": "unknown",
        "warnings": [],
        "errors": [],
    }
    # Dependency review is enabled via Dependabot or security settings
    dep_review_url = (
        f"https://api.github.com/repos/{owner}/{repo}/dependency-graph/snapshots"
    )
    status, _ = api_get(dep_review_url, token)
    results["dependency_review"] = "available" if status == 200 else "unavailable"
    # CodeQL setup
    codeql_url = f"https://api.github.com/repos/{owner}/{repo}/code-scanning/setup"
    status, data = api_get(codeql_url, token)
    if status == 200 and isinstance(data, dict):
        results["codeql"] = "enabled"
    elif status == 404:
        results["codeql"] = "disabled"
    else:
        results["codeql"] = "unknown"
    # Secret scanning
    ss_url = f"https://api.github.com/repos/{owner}/{repo}/secret-scanning"
    status, data = api_get(ss_url, token)
    if status == 200 and isinstance(data, dict):
        results[_SECRET_SCANNING] = "enabled"
        results["push_protection"] = (
            "enabled" if data.get("push_protection_enabled") else "disabled"
        )
    elif status == 404:
        results[_SECRET_SCANNING] = "disabled"
        results["push_protection"] = "disabled"
    else:
        results["warnings"].append(f"Secret Scanning API returned HTTP {status}")
    # Dependabot alerts
    da_url = f"https://api.github.com/repos/{owner}/{repo}/dependabot/alerts"
    status, _ = api_get(da_url, token)
    results["dependabot_alerts"] = (
        "enabled" if status == 200 else "disabled_or_unavailable"
    )
    # Dependabot security updates
    dsu_url = f"https://api.github.com/repos/{owner}/{repo}/dependabot/updates"
    status, data = api_get(dsu_url, token)
    if status == 200 and isinstance(data, list):
        results["dependabot_security_updates"] = "enabled"
    else:
        results["dependabot_security_updates"] = "disabled_or_unavailable"
    # SBOM
    sbom_url = f"https://api.github.com/repos/{owner}/{repo}/sbom"
    status, _ = api_get(sbom_url, token)
    results["sbom"] = "available" if status == 200 else "unavailable"
    # Artifact attestations
    att_url = f"https://api.github.com/repos/{owner}/{repo}/attestations"
    status, _ = api_get(att_url, token)
    results["artifact_attestations"] = "available" if status == 200 else "unavailable"
    # OIDC - check for OIDC policy in actions settings
    oidc_url = f"https://api.github.com/repos/{owner}/{repo}/actions/oidc"
    status, _ = api_get(oidc_url, token)
    results["oidc"] = "available" if status == 200 else "unavailable"
    return results


def validate_workflow_security(
    owner: str, repo: str, token: str | None
) -> dict[str, Any]:
    results: dict[str, Any] = {
        "default_permissions": "unknown",
        "findings": [],
        "warnings": [],
        "errors": [],
    }
    repo_url = f"https://api.github.com/repos/{owner}/{repo}"
    status, data = api_get(repo_url, token)
    if status == 200 and isinstance(data, dict):
        results["default_permissions"] = data.get("default_branch", "unknown")
    else:
        results["warnings"].append(
            "Could not fetch repository settings for workflow security audit"
        )
    return results


def validate_merge_queue(protection: dict[str, Any]) -> dict[str, Any]:
    allow_force_pushes_bypass = protection.get("checks", {}).get(
        "allow_force_pushes_bypass", {}
    )
    if isinstance(allow_force_pushes_bypass, dict):
        enabled = allow_force_pushes_bypass.get("enabled", False)
        return {"enabled": enabled, "warning": None}
    return {"enabled": False, "warning": "Merge queue configuration unavailable"}


def _render_single_branch_protection(  # noqa: C901
    branch_name: str,
    protection: dict[str, Any],
    required_checks: list[str],
) -> tuple[list[str], int, int, int]:
    lines: list[str] = []
    critical_delta = 0
    score_delta = 0
    warning_delta = 0
    if not protection.get("exists"):
        lines.append(f"- **{branch_name}**: ❌ FAIL — Branch protection is not enabled")
        critical_delta += 1
        score_delta -= 25
        return lines, critical_delta, score_delta, warning_delta
    lines.append(f"- **{branch_name}**: ✅ Enabled")
    contexts = protection.get("checks", {}).get("contexts", [])
    missing = [c for c in required_checks if c not in contexts]
    if missing:
        lines.append(f"  - Required checks: ❌ Missing: {', '.join(missing)}")
        critical_delta += 1
        score_delta -= 15
    else:
        lines.append(
            f"  - Required checks: ✅ All {len(required_checks)} checks present"
        )
    checks = protection.get("checks", {})
    if checks.get("allow_force_pushes"):
        lines.append("  - Force push: ❌ FAIL — Force push is enabled")
        critical_delta += 1
        score_delta -= 15
    else:
        lines.append("  - Force push: ✅ Disabled")
    if checks.get("allow_deletions"):
        lines.append("  - Branch deletion: ❌ FAIL — Branch deletion is enabled")
        critical_delta += 1
        score_delta -= 15
    else:
        lines.append("  - Branch deletion: ✅ Disabled")
    if checks.get("enforce_admins"):
        lines.append("  - Admin enforcement: ✅ Admins must obey rules")
    else:
        lines.append("  - Admin enforcement: ❌ FAIL — Admins can bypass")
        critical_delta += 1
        score_delta -= 10
    if checks.get("required_conversation_resolution"):
        lines.append("  - Conversation resolution: ✅ Required")
    else:
        lines.append("  - Conversation resolution: ⚠️ Not required")
        warning_delta += 1
    approve_count = checks.get("required_approving_review_count")
    if approve_count and approve_count >= REQUIRED_REVIEWS_MIN:
        lines.append(f"  - Required reviews: ✅ {approve_count} approvals")
    else:
        actual = approve_count if approve_count is not None else 0
        lines.append(
            f"  - Required reviews: ❌ FAIL — {actual} approvals "
            f"(expected >= {REQUIRED_REVIEWS_MIN})"
        )
        critical_delta += 1
        score_delta -= 10
    if checks.get("dismiss_stale_reviews"):
        lines.append("  - Dismiss stale reviews: ✅ Enabled")
    else:
        lines.append("  - Dismiss stale reviews: ⚠️ Disabled")
        warning_delta += 1
    if checks.get("require_code_owner_reviews"):
        lines.append("  - Code owner reviews: ✅ Required")
    else:
        lines.append("  - Code owner reviews: ⚠️ Not required")
        warning_delta += 1
    if checks.get("required_linear_history"):
        lines.append("  - Linear history: ✅ Required")
    else:
        lines.append("  - Linear history: ⚠️ Not required")
        warning_delta += 1
    allowed = checks.get("allowed_merge_methods", [])
    if allowed:
        lines.append(f"  - Merge methods: {', '.join(allowed)}")
    else:
        lines.append("  - Merge methods: ⚠️ Not configured")
    return lines, critical_delta, score_delta, warning_delta


def _render_branch_protection_section(
    main_protection: dict[str, Any],
    master_protection: dict[str, Any],
    required_checks: list[str],
) -> tuple[list[str], int, int, int]:
    lines: list[str] = ["## Branch Protection"]
    critical_delta = 0
    score_delta = 0
    warning_delta = 0
    for branch_name, protection in [
        ("main", main_protection),
        ("master", master_protection),
    ]:
        branch_lines, crit, score, warn = _render_single_branch_protection(
            branch_name=branch_name,
            protection=protection,
            required_checks=required_checks,
        )
        lines.extend(branch_lines)
        critical_delta += crit
        score_delta += score
        warning_delta += warn
    lines.append("")
    return lines, critical_delta, score_delta, warning_delta


def _render_merge_queue_section(
    main_protection: dict[str, Any],
    master_protection: dict[str, Any],
) -> tuple[list[str], int]:
    lines: list[str] = ["## Merge Queue"]
    warning_delta = 0
    merge_queue = validate_merge_queue(
        main_protection if main_protection.get("exists") else master_protection
    )
    if merge_queue.get("enabled"):
        lines.append("- Status: ✅ Enabled")
    else:
        warning = merge_queue.get("warning")
        lines.append(f"- Status: ⚠️ Disabled{f' ({warning})' if warning else ''}")
        warning_delta += 1
    lines.append("")
    return lines, warning_delta


def _render_rulesets_section(rulesets: dict[str, Any]) -> tuple[list[str], int]:
    lines: list[str] = ["## Rulesets"]
    warning_delta = 0
    if rulesets.get("count", 0) > 0:
        lines.append(f"- Count: {rulesets['count']}")
        for rs in rulesets.get("rulesets", []):
            lines.append(
                f"  - `{rs.get('name')}` ({rs.get('target')}) — {rs.get('enforcement')}"
            )
    else:
        lines.append("- Status: ⚠️ No rulesets configured")
        warning_delta += 1
    lines.append("")
    return lines, warning_delta


def _render_security_features_section(
    security_features: dict[str, Any],
) -> tuple[list[str], int]:
    lines: list[str] = ["## Security Features"]
    warning_delta = 0
    for feature, value in security_features.items():
        if feature in {"warnings", "errors"}:
            continue
        display = value.replace("_", " ").title()
        if value in {"enabled", "available"}:
            lines.append(f"- {display}: ✅ {value.title()}")
        elif value in {"disabled"}:
            lines.append(f"- {display}: ⚠️ Disabled")
            warning_delta += 1
        else:
            lines.append(f"- {display}: ⚠️ Unable to verify")
            warning_delta += 1
    lines.append("")
    return lines, warning_delta


def _render_workflow_security_section(
    workflow_security: dict[str, Any],
) -> tuple[list[str], int]:
    lines: list[str] = ["## Workflow Security"]
    warning_delta = 0
    if workflow_security.get("warnings"):
        lines.append(
            f"- ⚠️ {len(workflow_security['warnings'])} workflow security "
            f"warnings detected"
        )
    else:
        lines.append("- ✅ No dangerous workflow permissions detected")
    lines.append("")
    return lines, warning_delta


def _render_workflow_integrity_section(
    workflow_integrity: dict[str, Any],
) -> tuple[list[str], int, int]:
    lines: list[str] = ["## Workflow Integrity"]
    critical_delta = 0
    score_delta = 0
    if workflow_integrity.get("missing"):
        lines.append(
            f"- ❌ Missing workflows: {', '.join(workflow_integrity['missing'])}"
        )
        critical_delta += 1
        score_delta -= 20
    else:
        lines.append("- ✅ All critical workflows present")
    lines.append("")
    return lines, critical_delta, score_delta


def _render_overall_section(
    overall_score: int, critical_failures: int, warning_count: int
) -> list[str]:
    lines: list[str] = ["## Overall Score"]
    lines.append(f"Score: {overall_score}/100")
    if critical_failures > 0:
        lines.append(f"Status: ❌ FAIL — {critical_failures} critical failure(s)")
    else:
        lines.append(f"Status: ✅ PASS — {warning_count} warning(s)")
    lines.append("")
    lines.append(REPORT_FOOTER)
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description="Branch Protection Validator")
    parser.add_argument("--json", action="store_true", help="Output report as JSON")
    parser.add_argument("--token", help="GitHub token override")
    parser.add_argument("--repo", help="Repository override (owner/repo)")
    parser.add_argument(
        "--required-checks", help="Comma-separated required check names"
    )
    args = parser.parse_args()

    token = args.token or get_token()
    if not token:
        print("SKIPPED: GITHUB_TOKEN or GH_TOKEN is not available.")
        return 0

    repo_info_input = args.repo or os.environ.get("GITHUB_REPOSITORY")
    if not repo_info_input or "/" not in repo_info_input:
        print("SKIPPED: Repository could not be determined.")
        return 0
    owner, repo = repo_info_input.split("/", 1)

    required_checks = DEFAULT_REQUIRED_CHECKS
    if args.required_checks:
        required_checks = [
            c.strip() for c in args.required_checks.split(",") if c.strip()
        ]

    main_protection = validate_branch_protection(owner, repo, "main", token)
    master_protection = validate_branch_protection(owner, repo, "master", token)
    repo_settings = validate_repo_info(owner, repo, token)
    rulesets = validate_rulesets(owner, repo, token)
    workflow_integrity = validate_workflow_integrity(owner, repo, token)
    security_features = validate_security_features(owner, repo, token)
    workflow_security = validate_workflow_security(owner, repo, token)

    # Determine primary protection (main if exists, otherwise master)
    main_protection if main_protection.get("exists") else master_protection

    if args.json:
        payload = {
            "repository": f"{owner}/{repo}",
            "main_protection": main_protection,
            "master_protection": master_protection,
            "repo_info": repo_settings,
            "rulesets": rulesets,
            "workflow_integrity": workflow_integrity,
            "security_features": security_features,
            "workflow_security": workflow_security,
        }
        print(json.dumps(payload, indent=2, default=str))
        return 0

    lines: list[str] = [REPORT_HEADER, ""]
    lines.append(f"Repository: `{owner}/{repo}`")
    lines.append(
        f"Default branch: `{repo_settings.get('default_branch') or 'unknown'}`"
    )
    lines.append("")
    overall_score = 100
    critical_failures = 0
    warning_count = 0

    section_lines, crit_delta, score_delta, warn_delta = (
        _render_branch_protection_section(
            main_protection=main_protection,
            master_protection=master_protection,
            required_checks=required_checks,
        )
    )
    lines.extend(section_lines)
    critical_failures += crit_delta
    overall_score += score_delta
    warning_count += warn_delta

    section_lines, warn_delta = _render_merge_queue_section(
        main_protection=main_protection,
        master_protection=master_protection,
    )
    lines.extend(section_lines)
    warning_count += warn_delta

    section_lines, warn_delta = _render_rulesets_section(rulesets=rulesets)
    lines.extend(section_lines)
    warning_count += warn_delta

    section_lines, warn_delta = _render_security_features_section(
        security_features=security_features,
    )
    lines.extend(section_lines)
    warning_count += warn_delta

    section_lines, warn_delta = _render_workflow_security_section(
        workflow_security=workflow_security,
    )
    lines.extend(section_lines)
    warning_count += warn_delta

    section_lines, crit_delta, score_delta = _render_workflow_integrity_section(
        workflow_integrity=workflow_integrity,
    )
    lines.extend(section_lines)
    critical_failures += crit_delta
    overall_score += score_delta

    lines.extend(
        _render_overall_section(
            overall_score=overall_score,
            critical_failures=critical_failures,
            warning_count=warning_count,
        )
    )
    report = "\n".join(lines)
    print(report)

    # Exit 1 only if critical failures exist
    critical_failures = sum(
        1
        for p in [main_protection, master_protection]
        for e in p.get("errors", [])
        if "not enabled" in e or "Missing" in e
    )
    critical_failures += len(workflow_integrity.get("errors", []))
    return 1 if critical_failures > 0 else 0


if __name__ == "__main__":
    sys.exit(main())
