"""Validate coverage.xml completeness against the .coverage database.

Ensures every measured source file appears in the Cobertura XML with a
unique relative filename. Exits non-zero if SonarCloud would receive
an incomplete coverage report.
"""

from __future__ import annotations

import os
import sqlite3
import sys
import xml.etree.ElementTree as ET  # noqa: S314 - coverage.xml is generated by our trusted CI pipeline

SOURCE_DIRS = [
    "rentsecure_be",
    "ai_assistant",
    "core",
    "dashboard",
    "documents",
    "finance",
    "notification",
    "properties",
    "referral_and_earn",
    "smartbot",
]


def _project_root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _measured_files(project_root: str) -> list[str]:
    db_path = os.path.join(project_root, ".coverage")
    if not os.path.exists(db_path):
        print(f"ERROR: .coverage database not found at {db_path}")
        sys.exit(2)

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute("SELECT path FROM file")
    rows = cursor.fetchall()
    conn.close()
    return [r[0] for r in rows]


def _xml_classes(xml_path: str) -> tuple[list[dict], int, int]:
    if not os.path.exists(xml_path):
        print(f"ERROR: coverage.xml not found at {xml_path}")
        sys.exit(3)

    tree = (
        ET.parse(  # noqa: S314 - coverage.xml is generated by our trusted CI pipeline
            xml_path
        )
    )
    root = tree.getroot()
    sources = [s.text for s in root.findall(".//source") if s.text is not None]

    classes: list[dict] = []
    for cls in root.iter("class"):
        if cls.tag != "class":
            continue
        filename = cls.get("filename", "")
        resolved_abs: str | None = None
        for src in sources:
            candidate = os.path.join(src, filename)
            if os.path.exists(candidate):
                resolved_abs = os.path.abspath(candidate)
                break
        if resolved_abs is None:
            # Preserve the filename so diagnostics still show what's in the XML
            resolved_abs = filename
        classes.append(
            {
                "filename": filename,
                "resolved_abs": resolved_abs,
            }
        )

    lines_valid = int(root.get("lines-valid", "0") or "0")
    lines_covered = int(root.get("lines-covered", "0") or "0")
    return classes, lines_valid, lines_covered


def _discover_collisions(classes: list[dict]) -> dict[str, list[str]]:
    collisions: dict[str, list[str]] = {}
    for cls in classes:
        fn = cls["filename"]
        collisions.setdefault(fn, []).append(cls["resolved_abs"])
    return {k: v for k, v in collisions.items() if len(v) > 1}


def _normalize_abs_path(path: str) -> str:
    return os.path.normcase(os.path.normpath(path))


def main() -> int:
    project_root = _project_root()
    measured = _measured_files(project_root)
    xml_path = os.path.join(project_root, "coverage.xml")
    classes, xml_lines_valid, xml_lines_covered = _xml_classes(xml_path)

    measured_set = {_normalize_abs_path(p) for p in measured}
    xml_set = {_normalize_abs_path(c["resolved_abs"]) for c in classes}

    missing = measured_set - xml_set
    collisions = _discover_collisions(classes)

    print("=" * 60)
    print("COVERAGE XML VALIDATION")
    print("=" * 60)
    print(f"Project root       : {project_root}")
    print(f".coverage files    : {len(measured)}")
    print(f"XML classes        : {len(classes)}")
    print(f"Missing files      : {len(missing)}")
    print(f"Duplicate filenames: {len(collisions)}")
    print()

    if not measured:
        print("ERROR: .coverage database contains no measured files.")
        print("Expected 140+ files; check that coverage combine succeeded.")
        return 1

    if not classes:
        print("ERROR: coverage.xml contains no <class> elements.")
        print("Expected 140+ classes; check that coverage xml succeeded.")
        return 1

    if missing:
        print("ERROR: The following measured files are absent from coverage.xml:")
        for path in sorted(missing):
            print(f"  MISSING: {path}")
        print()
        print("SonarCloud would treat these files as 0% covered,")
        print("which artificially lowers the overall coverage percentage.")
        return 1

    if collisions:
        print("ERROR: Duplicate relative filenames detected in coverage.xml:")
        for fn, paths in sorted(collisions.items()):
            print(f"  filename={fn}")
            for p in paths:
                print(f"    -> {p}")
        print()
        print(
            "Duplicate filenames indicate that coverage.py silently overwrote"
            "\nfile entries during Cobertura XML generation."
        )
        return 1

    if xml_lines_valid > 0:
        line_rate_pct = xml_lines_covered / xml_lines_valid * 100
        print(f"XML top-level line-rate   : {line_rate_pct:.2f}%")
    print()
    print("OK: All measured files are present with unique relative filenames.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
