# Generated by Django 5.2.1 on 2025-05-23 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_concierge_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrecord',
            name='property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner_rent_records', to='wealth_concierge_platform.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentrecord',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_rent_records', to='wealth_concierge_platform.renter'),
        ),
    ]
