# Generated by Django 5.2.1 on 2026-04-21 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_concierge_platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrenter',
            name='final_invoice_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='flagged_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='is_agreement_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='late_payment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='missed_rents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='notice_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='revocation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='revoked_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='revoked_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('notice_period', 'Notice Period'), ('revoked', 'Revoked'), ('deactivated', 'Deactivated')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='vacated_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrentrecord',
            name='adjustment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrentrecord',
            name='grace_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='historicalrentrecord',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalrentrecord',
            name='invoice_pdf',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalrentrecord',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='historicalunit',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='vacant', max_length=20),
        ),
        migrations.AddField(
            model_name='renter',
            name='final_invoice_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='flagged_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='is_agreement_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='renter',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='renter',
            name='late_payment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='renter',
            name='missed_rents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='renter',
            name='notice_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='revocation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='revoked_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='renter',
            name='revoked_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('notice_period', 'Notice Period'), ('revoked', 'Revoked'), ('deactivated', 'Deactivated')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='renter',
            name='vacated_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentrecord',
            name='adjustment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentrecord',
            name='grace_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='rentrecord',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rentrecord',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='rent_invoices/'),
        ),
        migrations.AddField(
            model_name='rentrecord',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='vacant', max_length=20),
        ),
        migrations.CreateModel(
            name='AgreementRevocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wealth_concierge_platform.renter')),
                ('revoked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedRenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('agreement_pdf', models.FileField(upload_to='archived/agreements/')),
                ('police_pdf', models.FileField(upload_to='archived/police/')),
                ('property_images', models.JSONField(default=list)),
                ('final_invoice', models.FileField(upload_to='archived/final_invoice/')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('renter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wealth_concierge_platform.renter')),
            ],
        ),
        migrations.CreateModel(
            name='UnitVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('renovation', 'Renovation'), ('cleaning', 'Cleaning'), ('between renters', 'Between Renters'), ('long-term vacancy', 'Long-Term Vacancy'), ('other', 'Other')], max_length=100)),
                ('noted_on', models.DateField(auto_now_add=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wealth_concierge_platform.unit')),
            ],
        ),
    ]
