# Generated by Django 5.2.1 on 2025-05-23 21:07

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_concierge_platform', '0002_rentrecord_property_alter_rentrecord_renter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCaretaker',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(help_text="Caretaker's full name", max_length=100)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate phone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact name', max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('caretaker_image', models.TextField(blank=True, help_text='Photo of caretaker', max_length=100, null=True)),
                ('id_proof', models.TextField(help_text="Caretaker's ID proof document", max_length=100)),
                ('address_line', models.CharField(help_text='Caretaker address line', max_length=255)),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark', max_length=255, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State', max_length=100)),
                ('country', models.CharField(help_text='Country', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal code', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Start date of caretaker service', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date of caretaker service', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical caretaker',
                'verbose_name_plural': 'historical caretakers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProperty',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('title', models.CharField(help_text='Title of the property', max_length=100)),
                ('address_line', models.CharField(help_text='Street address', max_length=255)),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark', max_length=255, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State', max_length=100)),
                ('country', models.CharField(help_text='Country', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal code', max_length=20)),
                ('property_type', models.CharField(choices=[('land', 'Land'), ('flat', 'Flat'), ('commercial_shop', 'Commercial Shop'), ('house', 'House'), ('villa', 'Villa'), ('office', 'Office')], help_text='Type of property', max_length=50)),
                ('property_image', models.TextField(blank=True, help_text='Image of property', max_length=100, null=True)),
                ('id_proof', models.TextField(help_text='Owner ID proof document', max_length=100)),
                ('is_vacant', models.BooleanField(default=True, help_text='Is property currently vacant?')),
                ('is_verified', models.BooleanField(default=False, help_text='Has property been verified?')),
                ('maintenance_notes', models.TextField(blank=True, help_text='Maintenance related notes', null=True)),
                ('rent_due_reminder', models.BooleanField(default=True, help_text='Enable rent due reminders?')),
                ('agreement_expiry_reminder', models.BooleanField(default=True, help_text='Enable agreement expiry reminders?')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical property',
                'verbose_name_plural': 'historical propertys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRenter',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(help_text="Renter's full name", max_length=100)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate phone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact name', max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('renter_image', models.TextField(blank=True, help_text='Photo of renter', max_length=100, null=True)),
                ('id_proof', models.TextField(help_text="Renter's ID proof document", max_length=100)),
                ('rent_agreement', models.TextField(help_text='Rent agreement document', max_length=100)),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Rent amount', max_digits=10)),
                ('start_date', models.DateField(help_text='Rental start date')),
                ('end_date', models.DateField(blank=True, help_text='Rental end date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is renter currently active?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical renter',
                'verbose_name_plural': 'historical renters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRentRecord',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('rent_month', models.DateField(help_text='Use first day of the month, e.g. 2025-05-01')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid for rent', max_digits=10)),
                ('date_paid', models.DateField(help_text='Date when payment was made')),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Transfer'), ('other', 'Other')], help_text='Mode of payment', max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical rent record',
                'verbose_name_plural': 'historical rent records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='caretaker',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='renter',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='address_line',
            field=models.CharField(help_text='Caretaker address line', max_length=255),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate phone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='caretaker_image',
            field=models.ImageField(blank=True, help_text='Photo of caretaker', null=True, upload_to='caretaker_images/'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='city',
            field=models.CharField(help_text='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='country',
            field=models.CharField(help_text='Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='emergency_contact_number',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of caretaker service', null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='id_proof',
            field=models.FileField(help_text="Caretaker's ID proof document", upload_to='id_proofs/caretakers/'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='name',
            field=models.CharField(help_text="Caretaker's full name", max_length=100),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes', null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='phone',
            field=models.CharField(help_text='Primary phone number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='postal_code',
            field=models.CharField(help_text='Postal code', max_length=20),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of caretaker service', null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='state',
            field=models.CharField(help_text='State', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='address_line',
            field=models.CharField(help_text='Street address', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='agreement_expiry_reminder',
            field=models.BooleanField(default=True, help_text='Enable agreement expiry reminders?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(help_text='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(help_text='Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='id_proof',
            field=models.FileField(help_text='Owner ID proof document', upload_to='id_proofs/owners/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_vacant',
            field=models.BooleanField(default=True, help_text='Is property currently vacant?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has property been verified?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='maintenance_notes',
            field=models.TextField(blank=True, help_text='Maintenance related notes', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(help_text='Postal code', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(blank=True, help_text='Image of property', null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('land', 'Land'), ('flat', 'Flat'), ('commercial_shop', 'Commercial Shop'), ('house', 'House'), ('villa', 'Villa'), ('office', 'Office')], help_text='Type of property', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_due_reminder',
            field=models.BooleanField(default=True, help_text='Enable rent due reminders?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(help_text='State', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(help_text='Title of the property', max_length=100),
        ),
        migrations.AlterField(
            model_name='renter',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate phone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='renter',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='renter',
            name='emergency_contact_number',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='renter',
            name='end_date',
            field=models.DateField(blank=True, help_text='Rental end date', null=True),
        ),
        migrations.AlterField(
            model_name='renter',
            name='id_proof',
            field=models.FileField(help_text="Renter's ID proof document", upload_to='id_proofs/renters/'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is renter currently active?'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='name',
            field=models.CharField(help_text="Renter's full name", max_length=100),
        ),
        migrations.AlterField(
            model_name='renter',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes', null=True),
        ),
        migrations.AlterField(
            model_name='renter',
            name='phone',
            field=models.CharField(help_text='Primary phone number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='renter',
            name='rent_agreement',
            field=models.FileField(help_text='Rent agreement document', upload_to='agreements/'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, help_text='Rent amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='renter',
            name='renter_image',
            field=models.ImageField(blank=True, help_text='Photo of renter', null=True, upload_to='renter_images/'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='start_date',
            field=models.DateField(help_text='Rental start date'),
        ),
        migrations.AlterField(
            model_name='rentrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid for rent', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentrecord',
            name='date_paid',
            field=models.DateField(help_text='Date when payment was made'),
        ),
        migrations.AlterField(
            model_name='rentrecord',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Transfer'), ('other', 'Other')], help_text='Mode of payment', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentrecord',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_records', to='wealth_concierge_platform.property'),
        ),
        migrations.AlterField(
            model_name='rentrecord',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks or notes', null=True),
        ),
        migrations.AlterField(
            model_name='rentrecord',
            name='rent_month',
            field=models.DateField(help_text='Use first day of the month, e.g. 2025-05-01'),
        ),
        migrations.AlterField(
            model_name='rentrecord',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_records', to='wealth_concierge_platform.renter'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='wealth_conc_city_6c1622_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner'], name='wealth_conc_owner_i_d8e973_idx'),
        ),
        migrations.AddField(
            model_name='historicalcaretaker',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcaretaker',
            name='property',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wealth_concierge_platform.property'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrenter',
            name='property',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wealth_concierge_platform.property'),
        ),
        migrations.AddField(
            model_name='historicalrentrecord',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrentrecord',
            name='property',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wealth_concierge_platform.property'),
        ),
        migrations.AddField(
            model_name='historicalrentrecord',
            name='renter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wealth_concierge_platform.renter'),
        ),
    ]
