# Generated by Django 5.2.1 on 2025-05-24 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_concierge_platform', '0003_historicalcaretaker_historicalproperty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('elite', 'Elite')], max_length=50, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.TextField(help_text='Comma-separated list or rich description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddOnPurchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_yearly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wealth_concierge_platform.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersubscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTaxRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('online', 'Online'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('upi', 'UPI'), ('other', 'Other')], max_length=30, null=True)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='tax_proofs/')),
                ('proof_description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='wealth_concierge_platform.property')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tax_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('property', 'tax_year')},
            },
        ),
        migrations.CreateModel(
            name='PlanFeatureLimit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_key', models.CharField(choices=[('max_properties', 'Max Properties'), ('max_renters', 'Max Renters per Property'), ('max_property_images', 'Max Property Images'), ('max_document_uploads', 'Max Document Uploads'), ('tax_notifications', 'Tax Notifications'), ('whatsapp_alerts', 'WhatsApp Alerts'), ('rent_agreement_drafting', 'Rent Agreement Drafting'), ('export_pdf_dossier', 'Export PDF Dossier')], max_length=50)),
                ('value', models.CharField(max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='wealth_concierge_platform.subscriptionplan')),
            ],
            options={
                'unique_together': {('plan', 'feature_key')},
            },
        ),
        migrations.CreateModel(
            name='UsageLimit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_key', models.CharField(choices=[('max_properties', 'Max Properties'), ('max_renters', 'Max Renters per Property'), ('max_property_images', 'Max Property Images'), ('max_document_uploads', 'Max Document Uploads'), ('tax_notifications', 'Tax Notifications'), ('whatsapp_alerts', 'WhatsApp Alerts'), ('rent_agreement_drafting', 'Rent Agreement Drafting'), ('export_pdf_dossier', 'Export PDF Dossier')], max_length=50)),
                ('usage_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feature_key')},
            },
        ),
    ]
