# Generated by Django 5.2.1 on 2025-05-24 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_concierge_platform', '0004_subscriptionplan_addonpurchase_usersubscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='rent_reminder_days_before',
            field=models.PositiveIntegerField(default=7, help_text='Days before rent due date to send reminder'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='tax_reminder_days_before',
            field=models.PositiveIntegerField(default=7, help_text='Days before tax due date to send reminder'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='caretaker_image',
            field=models.ImageField(blank=True, help_text='Photo of caretaker', null=True, upload_to='caretaker_image/'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='id_proof',
            field=models.FileField(help_text="Caretaker's ID proof document", upload_to='id_proof/caretaker/'),
        ),
        migrations.AlterField(
            model_name='planfeaturelimit',
            name='feature_key',
            field=models.CharField(choices=[('max_properties', 'Max Properties'), ('max_renters', 'Max Renters per Property'), ('max_caretakers', 'Max Caretakers per Property'), ('max_property_images', 'Max Property Images'), ('max_document_uploads', 'Max Document Uploads'), ('tax_notifications', 'Tax Notifications'), ('whatsapp_alerts', 'WhatsApp Alerts'), ('rent_agreement_drafting', 'Rent Agreement Drafting'), ('export_pdf_dossier', 'Export PDF Dossier')], max_length=50),
        ),
        migrations.AlterField(
            model_name='renter',
            name='id_proof',
            field=models.FileField(help_text="Renter's ID proof document", upload_to='id_proofs/renter/'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='renter_image',
            field=models.ImageField(blank=True, help_text='Photo of renter', null=True, upload_to='renter_image/'),
        ),
        migrations.AlterField(
            model_name='usagelimit',
            name='feature_key',
            field=models.CharField(choices=[('max_properties', 'Max Properties'), ('max_renters', 'Max Renters per Property'), ('max_caretakers', 'Max Caretakers per Property'), ('max_property_images', 'Max Property Images'), ('max_document_uploads', 'Max Document Uploads'), ('tax_notifications', 'Tax Notifications'), ('whatsapp_alerts', 'WhatsApp Alerts'), ('rent_agreement_drafting', 'Rent Agreement Drafting'), ('export_pdf_dossier', 'Export PDF Dossier')], max_length=50),
        ),
        migrations.CreateModel(
            name='PDFExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wealth_concierge_platform.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='property_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wealth_concierge_platform.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wealth_concierge_platform.property')),
            ],
        ),
        migrations.CreateModel(
            name='RentAgreementDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='auto_agreements/')),
                ('renter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wealth_concierge_platform.renter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
