# Generated by Django 5.2 on 2026-08-08

from django.db import migrations, models
import django.db.models.deletion
import visitors.models.visitor_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(
                        help_text="Full name of the visitor", max_length=100
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Primary contact number of the visitor", max_length=15
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Visitor email address (optional)",
                        max_length=254,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Visitor photo",
                        null=True,
                        upload_to="visitor_photos/",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("personal_visit", "Personal Visit"),
                            ("family_visit", "Family Visit"),
                            ("business_meeting", "Business Meeting"),
                            ("service_personnel", "Service Personnel"),
                            ("maintenance", "Maintenance / Repair"),
                            ("delivery", "Delivery / Courier"),
                            ("emergency", "Emergency"),
                            ("other", "Other"),
                        ],
                        default="personal_visit",
                        help_text="Reason for the visit",
                        max_length=30,
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(help_text="Date of the scheduled visit"),
                ),
                (
                    "expected_arrival",
                    models.DateTimeField(help_text="Expected arrival date and time"),
                ),
                (
                    "expected_departure",
                    models.DateTimeField(help_text="Expected departure date and time"),
                ),
                (
                    "number_of_visitors",
                    models.PositiveIntegerField(
                        default=1, help_text="Total number of visitors in the group"
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vehicle number (if applicable)",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes about the visit",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=30,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of approval", null=True
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason for rejection"
                    ),
                ),
                (
                    "approver_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Phone of the person who approved",
                        max_length=15,
                    ),
                ),
                (
                    "approver_notes",
                    models.TextField(
                        blank=True, default="", help_text="Notes from the approver"
                    ),
                ),
                (
                    "qr_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique QR token for gate verification",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "qr_generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the QR code was generated",
                        null=True,
                    ),
                ),
                (
                    "qr_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="QR code expiry timestamp", null=True
                    ),
                ),
                (
                    "qr_max_uses",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of times this QR can be scanned",
                    ),
                ),
                (
                    "qr_used_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times the QR has been scanned"
                    ),
                ),
                (
                    "qr_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the QR was successfully verified at gate",
                    ),
                ),
                (
                    "qr_verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When QR was verified at gate", null=True
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        blank=True, help_text="Actual check-in timestamp", null=True
                    ),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(
                        blank=True, help_text="Actual check-out timestamp", null=True
                    ),
                ),
                (
                    "verified_by_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Phone of the verifier",
                        max_length=15,
                    ),
                ),
                (
                    "vehicle_details",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vehicle details at time of entry",
                        max_length=100,
                    ),
                ),
                (
                    "visit_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Visit duration in minutes (calculated on check-out)",
                        null=True,
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="OTP code for visitor verification",
                        max_length=6,
                    ),
                ),
                (
                    "otp_generated_at",
                    models.DateTimeField(
                        blank=True, help_text="When the OTP was generated", null=True
                    ),
                ),
                (
                    "otp_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="OTP expiry timestamp", null=True
                    ),
                ),
                (
                    "otp_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the OTP was successfully verified",
                    ),
                ),
                (
                    "otp_verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When the OTP was verified", null=True
                    ),
                ),
                (
                    "otp_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of OTP verification attempts"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this visitor request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_visitors",
                        to="core.user",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        help_text="Building being visited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitors",
                        to="properties.building",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this visitor request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_visitors",
                        to="core.user",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        help_text="Renter being visited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitors",
                        to="properties.renter",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit being visited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitors",
                        to="properties.unit",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Caretaker/user who verified this visitor at gate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_visitors",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "visit_date"],
                        name="visitors_vis_status_93d6d5_idx",
                    ),
                    models.Index(
                        fields=["renter", "status"],
                        name="visitors_vis_renter__5f6e44_idx",
                    ),
                    models.Index(
                        fields=["building", "status"],
                        name="visitors_vis_building_7b0e3b_idx",
                    ),
                    models.Index(
                        fields=["qr_token"], name="visitors_vis_qr_toke_3e1b2c_idx"
                    ),
                    models.Index(
                        fields=["created_by", "status"],
                        name="visitors_vis_created_4a5f66_idx",
                    ),
                    models.Index(
                        fields=["otp_code", "otp_expires_at"],
                        name="visitors_vis_otp_cod_7c2d88_idx",
                    ),
                ],
                "verbose_name": "Visitor",
                "verbose_name_plural": "Visitors",
            },
            bases=(models.Model,),
            managers=[
                (
                    "objects",
                    visitors.models.visitor_models.VisitorQuerySet.as_manager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitorHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("cancelled", "Cancelled"),
                            ("blocked", "Blocked"),
                            ("expired", "Expired"),
                            ("qr_generated", "QR Generated"),
                            ("qr_verified", "QR Verified"),
                            ("otp_generated", "OTP Generated"),
                            ("otp_verified", "OTP Verified"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional context (e.g., vehicle number, approver notes)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_history_actions",
                        to="core.user",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="visitors.visitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["visitor", "action", "created_at"],
                        name="visitors_hist_visitor_3f4a1b_idx",
                    )
                ],
                "verbose_name": "Visitor History",
                "verbose_name_plural": "Visitor Histories",
            },
        ),
    ]
