from __future__ import annotations

DEFAULT_TIMEOUT_SECONDS = 30
CACHE_TTL_SHORT = 300
CACHE_TTL_MEDIUM = 3600
CACHE_TTL_LONG = 86400
RETRY_ATTEMPTS = 3
BATCH_SIZE = 100

__all__ = [
    "DEFAULT_TIMEOUT_SECONDS",
    "CACHE_TTL_SHORT",
    "CACHE_TTL_MEDIUM",
    "CACHE_TTL_LONG",
    "RETRY_ATTEMPTS",
    "BATCH_SIZE",
]
